### ISSUE TITLE
Impossible to install the plugin

### ISSUE THREAD

**Issue by Brakor** [NLthijs48/AreaShop#167]
I just tried to install AreaShop v2.2.2 on my 1.9.4 server, by placing the AreaShop.jar in my "plugins" folder, but when i try to start my server, it doesn't detect the AS plugin and doesn't install it. Any solutions ? I also checked if it wasn't an incompatibility with another plugin, and it is not...

**Comment by NLthijs48** [comment]
Did you check your log file? If there are dependencies missing then that will be printed to the log. If you cannot find it please provide me the `latest.log` file.

**Comment by Brakor** [comment]
I didn't check it, but now I did and i found this :
[20:26:41] [Server thread/ERROR]: Could not load 'plugins\AreaShop.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Vault
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot.jar:git-Spigot-4af49dc-23da8b0]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugins(CraftServer.java:296) [spigot.jar:git-Spigot-4af49dc-23da8b0]
	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:200) [spigot.jar:git-Spigot-4af49dc-23da8b0]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot.jar:git-Spigot-4af49dc-23da8b0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[20:26:41] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****

**Comment by NLthijs48** [comment]
You need to install [Vault](http://dev.bukkit.org/bukkit-plugins/vault/) and an Economy plugin, that is why it does not startup correctly.

**Comment by Brakor** [comment]
Ok i'm gonna try this, thanks bro :)

**Comment by Brakor** [comment]
Unfortunately, it doesn't work, and the error message in logs is still there ...

**Comment by NLthijs48** [comment]
Is it exactly the same error or not? Is there any error from Vault itself? If Vault is not in the output of `/plugins` then it has not been installed correctly yet.

**Comment by Brakor** [comment]
Ok so there is the "new" log error, so i downloaded worldGuard [20:40:55] [Server thread/ERROR]: Could not load 'plugins\AreaShop.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: WorldGuard
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot.jar:git-Spigot-4af49dc-23da8b0]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugins(CraftServer.java:296) [spigot.jar:git-Spigot-4af49dc-23da8b0]
	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:200) [spigot.jar:git-Spigot-4af49dc-23da8b0]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot.jar:git-Spigot-4af49dc-23da8b0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[20:40:55] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.1.2;b3fbe8b

And guess what, after installing it, it works :D Thanks for you help, mate :)

**Comment by NLthijs48** [comment]
Great, it helps to read the requirements next time ;)
