### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by EvilOlaf** [NLthijs48/AreaShop#182]
#### Update: WG 6.1.3 breaks something with AS, see below

 Just upgraded everything from 1.8 to 1.10. AS seem not to like it very much ^^

This comes on startup after everything else has finished loading.
```
[16:43:52 ERROR]: Could not pass event RegionUpdateEvent to AreaShop v2.2.2
java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.flags.DefaultFlag.fuzzyMatchFlag(Ljava/lang/String;)Lcom/sk89q/worldguard/protection/flags/Flag;
        at nl.evolutioncoding.areashop.features.WorldGuardRegionFlagsFeature.updateRegionFlags(WorldGuardRegionFlagsFeature.java:93) ~[?:?]
        at nl.evolutioncoding.areashop.features.WorldGuardRegionFlagsFeature.regionUpdate(WorldGuardRegionFlagsFeature.java:26) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor542.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[PaperSpigot-latest.jar:git-Paper-782]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-latest.jar:git-Paper-782]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-latest.jar:git-Paper-782]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [PaperSpigot-latest.jar:git-Paper-782]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [PaperSpigot-latest.jar:git-Paper-782]
        at nl.evolutioncoding.areashop.regions.GeneralRegion.update(GeneralRegion.java:185) [AreaShop.jar:?]
        at nl.evolutioncoding.areashop.managers.FileManager$3.run(FileManager.java:487) [AreaShop.jar:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) [PaperSpigot-latest.jar:git-Paper-782]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [PaperSpigot-latest.jar:git-Paper-782]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:802) [PaperSpigot-latest.jar:git-Paper-782]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) [PaperSpigot-latest.jar:git-Paper-782]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) [PaperSpigot-latest.jar:git-Paper-782]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [PaperSpigot-latest.jar:git-Paper-782]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

```

#### Steps to reproduce (for bugs)

Updated from 1.8.8 to 1.10, to be exact git-Paper-782
AreaShop updated to 2.2.2, was 2.2.1 before
Update WorldGuard to build 1679, was build 1653 before

#### Your environment

* Server platform (Bukkit, Spigot, etc.): git-Paper-782
* Server version: look above
* AreaShop version: 2.2.2
* WorldEdit version: 6.1.4-SNAPSHOT;3594-e1bb00e
* WorldGuard version: 6.1.3-SNAPSHOT;1679-f006a95
* Vault version: 1.5.6-b49

**Comment by EvilOlaf** [comment]
Just tried to unrent anyboys shop
```
[16:50:41 ERROR]: Could not pass event RegionUpdateEvent to AreaShop v2.2.2
java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.flags.DefaultFlag.fuzzyMatchFlag(Ljava/lang/String;)Lcom/sk89q/worldguard/protection/flags/Flag;
        at nl.evolutioncoding.areashop.features.WorldGuardRegionFlagsFeature.updateRegionFlags(WorldGuardRegionFlagsFeature.java:93) ~[?:?]
        at nl.evolutioncoding.areashop.features.WorldGuardRegionFlagsFeature.regionUpdate(WorldGuardRegionFlagsFeature.java:26) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor529.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-810]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.2.jar:git-Paper-810]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-810]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-810]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-810]
        at nl.evolutioncoding.areashop.regions.GeneralRegion.update(GeneralRegion.java:185) [AreaShop.jar:?]
        at nl.evolutioncoding.areashop.regions.GeneralRegion.notifyAndUpdate(GeneralRegion.java:194) [AreaShop.jar:?]
        at nl.evolutioncoding.areashop.regions.RentRegion.unRent(RentRegion.java:681) [AreaShop.jar:?]
        at nl.evolutioncoding.areashop.commands.UnrentCommand.execute(UnrentCommand.java:68) [AreaShop.jar:?]
        at nl.evolutioncoding.areashop.managers.CommandManager.onCommand(CommandManager.java:109) [AreaShop.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [patched_1.10.2.jar:git-Paper-810]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) [patched_1.10.2.jar:git-Paper-810]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:665) [patched_1.10.2.jar:git-Paper-810]
        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389) [patched_1.10.2.jar:git-Paper-810]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1194) [patched_1.10.2.jar:git-Paper-810]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.10.2.jar:git-Paper-810]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.10.2.jar:git-Paper-810]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-810]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-810]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:796) [patched_1.10.2.jar:git-Paper-810]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.10.2.jar:git-Paper-810]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) [patched_1.10.2.jar:git-Paper-810]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched_1.10.2.jar:git-Paper-810]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by EvilOlaf** [comment]
Aight, went back to WG 6.1.2 official release and it works again.
Seems like 6.1.3 breaks compatibility with AS.

**Comment by NLthijs48** [comment]
This problem is fixed in the [dev builds](http://wiefferink.me:8080/job/AreaShop/) of AreaShop, I will release a version of AreaShop soon. See #170 for more details.

I'm not entirely sure what the last error that you posted is, I'll look into that for a bit later.

**Comment by EvilOlaf** [comment]
Will test this.
Did not know that you do not use frostcast CI anymore.

**Comment by NLthijs48** [comment]
I have setup my own build server, which also updates the javadocs page etc, so that is why the dev builds are there now.

I have created issue #185 for adding the build number to the version string, will try to do that soon.
