### ISSUE TITLE
Small error thread-24

### ISSUE THREAD

**Issue by Noiknez** [NLthijs48/AreaShop#198]
#### Current behavior

Starting the server and get error :

> [16:06:59] [WARN] Exception in thread "Thread-24"
[16:06:59] [WARN] java.lang.NullPointerException
[16:06:59] [WARN] at me.wiefferink.areashop.lib.Updater.read(Updater.java:667)
[16:06:59] [WARN] at me.wiefferink.areashop.lib.Updater.runUpdater(Updater.java:723)
[16:06:59] [WARN] at me.wiefferink.areashop.lib.Updater.access$100(Updater.java:38)
[16:06:59] [WARN] at me.wiefferink.areashop.lib.Updater$UpdateRunnable.run(Updater.java:718)
[16:06:59] [WARN] at java.lang.Thread.run(Thread.java:745)

#### New behavior

The error should not be here

#### Steps to reproduce (for bugs)

1.  Starting a server

#### Your environment

* Server platform (Bukkit, Spigot, etc.): CraftBukkit version git-Spigot-af8198d-8cc5958 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
* Server version: 1.10.2
* AreaShop version: 2.3.0
* WorldEdit version: 6.1.3,7a097ca
* WorldGuard version: 6.1.2,e38d98d
* Vault version: 1.5.6-b49

**Comment by NLthijs48** [comment]
I suspect that BukkitDev has been offline for a moment, that is the site the update checker connects to to see if there is a new update. I have added a small fix to prevent this error from showing up, but I assume that the error does not happen anymore if you startup the server now right? This for sure does not affect the functioning of AreaShop, so the problem is minimal.

Thanks for reporting this though, I of course don't want AreaShop printing errors in the console.
