### ISSUE TITLE
NPE on as info

### ISSUE THREAD

**Issue by EvilOlaf** [NLthijs48/AreaShop#202]
```
[16:21:50] [Server thread/WARN]: [AreaShop] Command execution failed, command=areashop info region shop28, error=Unhandled exception executing command 'areashop' in plugin AreaShop v2.2.2, stacktrace:
[16:21:50] [Server thread/WARN]: [AreaShop] org.bukkit.command.CommandException: Unhandled exception executing command 'areashop' in plugin AreaShop v2.2.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
        at me.wiefferink.areashop.regions.GeneralRegion.runCommands(GeneralRegion.java:1583)
        at me.wiefferink.areashop.features.SignsFeature$RegionSign.runSignCommands(SignsFeature.java:334)
        at me.wiefferink.areashop.listeners.SignClickListener.onSignClick(SignClickListener.java:60)
        at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228)
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195)
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:107)
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:623)
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40)
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10)
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at me.wiefferink.areashop.commands.UnrentCommand.canUse(UnrentCommand.java:44)
        at me.wiefferink.areashop.commands.InfoCommand.execute(InfoCommand.java:169)
        at me.wiefferink.areashop.managers.CommandManager.onCommand(CommandManager.java:112)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        ... 27 more

[16:21:50] [Server thread/WARN]: [AreaShop] --- End of stacktrace ---
```

Not sure if this has been already fixed in a newer build. Though I am not on the latest version as the lang files are no longer compatbile.

#### Your environment

* Server platform (Bukkit, Spigot, etc.):  Spigot 
* Server version: 1.8.8
* AreaShop version: 2.2.2 (build 41)
* WorldEdit version: Bukkit-Official (6.1.2;b3fbe8b)
* WorldGuard version: WorldGuard 6.1.2-SNAPSHOT;1653-65e48d1
* Vault version: 1.5.6

**Comment by NLthijs48** [comment]
This has been fixed in ca7a9664f3d128a5d5f2717851be06d5a8884956, I just released AreaShop V2.3.2 which fixes the issue.

Note that only if you made a fully custom language file or if you translated to a language that is not included by default you have to watch out with the update, otherwise you are fine.

Thanks for the report.
