### ISSUE TITLE
NPE due to accessing non-existent config options

### ISSUE THREAD

**Issue by RoboMWM** [NLthijs48/AreaShop#247]
#### Current behavior
```
[08:46:58] [Server thread/ERROR]: Could not pass event UpdateRegionEvent to AreaShop v2.3.2#CUSTOM
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-916]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.2.jar:git-Paper-916]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-916]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-916]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-916]
	at me.wiefferink.areashop.regions.GeneralRegion.update(GeneralRegion.java:213) [AreaShop.jar:?]
	at me.wiefferink.areashop.managers.FileManager$3.run(FileManager.java:476) [AreaShop.jar:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.10.2.jar:git-Paper-916]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [patched_1.10.2.jar:git-Paper-916]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:798) [patched_1.10.2.jar:git-Paper-916]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-916]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [patched_1.10.2.jar:git-Paper-916]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-916]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at me.wiefferink.areashop.features.WorldGuardRegionFlagsFeature.updateRegionFlags(WorldGuardRegionFlagsFeature.java:60) ~[?:?]
	at me.wiefferink.areashop.features.WorldGuardRegionFlagsFeature.updateRegionFlags(WorldGuardRegionFlagsFeature.java:42) ~[?:?]
	at me.wiefferink.areashop.features.WorldGuardRegionFlagsFeature.regionUpdate(WorldGuardRegionFlagsFeature.java:22) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor708.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-916]
	... 13 more
```

And repeats for each region, I'm guessing

#### New behavior
No NPE's / test changes on a development branch

#### Steps to reproduce (for bugs)

1. Start server
2. Watch logspam

#### Your environment

* Server platform (Bukkit, Spigot, etc.): 
* Server version: 
* AreaShop version: https://github.com/NLthijs48/AreaShop/commit/1ba2e21ae9a1e2aed531f02770507066745f78ac
* WorldEdit version: 
* WorldGuard version: 
* Vault version: 

Ok I'm gonna guess it's all those changes in that commit. Would prefer if you could do development in a separate branch for those of us that build from source, if possible?

Update: Ok yea it is, probably need to implement a config converter.

**Comment by NLthijs48** [comment]
All of the changes in that commit are supposed to be backwards-compatible (everything I push to master should work, although is not always backwards-compatible, only releases are deemed safe to use). A bunch of config sections have moved from `config.yml` to `default.yml` in the commit, but AreaShop will still look at the old location if necessary.

I pushed a small fix that might do the trick, let me know if that works better with your configuration. Thank you for reporting the issue!

**Comment by RoboMWM** [comment]
Seems to be ok, haven't tested in-game yet but I don't see any NPEs on start now, thanks
