### ISSUE TITLE
Lot of exception since last version

### ISSUE THREAD

**Issue by jewome62** [NLthijs48/AreaShop#257]
```
03.12 22:02:54 [Server] WARN [AreaShop] Task #1913 for AreaShop v2.4.0 generated an exception 03.12 22:02:54 [Server] INFO java.lang.NullPointerException
03.12 22:02:54 [Server] INFO at me.wiefferink.areashop.regions.GeneralRegion.handleSchematicEvent(GeneralRegion.java:1740) ~[?:?]
03.12 22:02:54 [Server] INFO at me.wiefferink.areashop.regions.RentRegion.unRent(RentRegion.java:688) ~[?:?]
03.12 22:02:54 [Server] INFO at me.wiefferink.areashop.regions.RentRegion.checkExpiration(RentRegion.java:357) ~[?:?]
03.12 22:02:54 [Server] INFO at me.wiefferink.areashop.managers.FileManager$5.run(FileManager.java:636) ~[?:?]
03.12 22:02:54 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-f950f8e-b64d852]
03.12 22:02:54 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-f950f8e-b64d852]
03.12 22:02:54 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot.jar:git-Spigot-f950f8e-b64d852]
03.12 22:02:54 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-f950f8e-b64d852]
03.12 22:02:54 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-f950f8e-b64d852]
03.12 22:02:54 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-f950f8e-b64d852]
03.12 22:02:54 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

#### Your environment
* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: Spigot version: git-Spigot-f950f8e-b64d852 (MC: 1.11)
* AreaShop version: Last release, I try last dev build
* WorldEdit version: 6.1.5
* WorldGuard version: 6.2

I have 20GB of log since all update (I make it the 03/12/2016 02:15 GMT +2)

**Comment by NLthijs48** [comment]
Are you using the schematic save/restore feature? Because it looks like you have set the `schematicProfile` setting to a profile that does not exist. In the last update I made a mistake that causes this to print the error message you have, which I have fixed now.

It would be nice if you could send me a .zip of your `/plugin/AreaShop` folder to confirm the problem and see if I can do more to prevent it.

**Comment by jewome62** [comment]
My AreaShop plugin : https://jewome62.eu/owncloud/s/tlz94Lmq3LMmoUk

I admit i dont understand how active auto regen after rent
Maybe i have activate them wrongly

**Comment by jewome62** [comment]
I have not exception in lastest build
