### ISSUE TITLE
Exception on startup disable areashop

### ISSUE THREAD

**Issue by jewome62** [NLthijs48/AreaShop#266]
#### Current behavior
```
22.12 22:58:13 [Server] WARN [AreaShop] Task #5884 for AreaShop v2.4.0#108 generated an exception 22.12 22:58:13 [Server] INFO java.lang.NullPointerException 22.12 22:58:13 [Server] INFO at me.wiefferink.areashop.regions.GeneralRegion.addFeature(GeneralRegion.java:169) ~[?:?] 22.12 22:58:13 [Server] INFO at me.wiefferink.areashop.regions.GeneralRegion.setupFeatures(GeneralRegion.java:163) ~[?:?] 22.12 22:58:13 [Server] INFO at me.wiefferink.areashop.regions.GeneralRegion.<init>(GeneralRegion.java:139) ~[?:?] 22.12 22:58:13 [Server] INFO at me.wiefferink.areashop.regions.RentRegion.<init>(RentRegion.java:35) ~[?:?] 22.12 22:58:13 [Server] INFO at me.wiefferink.areashop.managers.FileManager$7.run(FileManager.java:903) ~[?:?] 22.12 22:58:13 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-f950f8e-b64d852] 22.12 22:58:13 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-f950f8e-b64d852] 22.12 22:58:13 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot.jar:git-Spigot-f950f8e-b64d852] 22.12 22:58:13 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-f950f8e-b64d852] 22.12 22:58:13 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-f950f8e-b64d852] 22.12 22:58:13 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-f950f8e-b64d852] 22.12 22:58:13 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

#### New behavior
AreaShop is not loaded

#### Steps to reproduce (for bugs)
Just Startup the server

#### Your environment (for bugs)
* Server platform Spigot
* Server version: 1.11.0
* AreaShop version: Build from 10 December
* WorldEdit version: 6.1.5
* WorldGuard version: 6.1.3 SNAPSHOT
* Vault version: 1.5.6

#### Your config files (for bugs)
https://jewome62.eu/owncloud/s/b5hS9rLhXFHUvJe

**Comment by NLthijs48** [comment]
The latest development builds are broken, sorry about that! I'm currently working on a fix so as soon as there is a development build with a date later than now then it should be good. Meanwhile revert to #106 or lower, or just take a [stable release](https://github.com/NLthijs48/AreaShop/releases).

**Comment by jewome62** [comment]
Thanks your fast fix.

I try this tonight.

\o/
Merry Christmas

**Comment by NLthijs48** [comment]
Merry Christmas to you too!

**Comment by jewome62** [comment]
That work !

Thanks, bye bye
