### ISSUE TITLE
Issure

### ISSUE THREAD

**Issue by Tombraxis** [NLthijs48/AreaShop#269]
#### Current behavior
not working when writing sign and makign command

#### Steps to reproduce (for bugs)
1. 
2. 
3. 
4. 

#### Your environment (for bugs)
1.7.10 
server platform: KCauldron1647.201 
* AreaShop version: V2.0.2
* WorldEdit version: 
* WorldGuard version: 
* Vault version: 

####LOG
####for command: /as add rent ...

org.bukkit.command.CommandException: Unhandled exception executing command 'as' in plugin AreaShop v2.0.2

	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-R0.1-SNAPSHOT]

	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-R0.1-SNAPSHOT]

	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-R0.1-SNAPSHOT]

	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]

	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]

	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]

	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]

	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]

	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]

	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]

	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]

	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]

	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]

	at java.lang.Thread.run(Thread.java:722) [?:1.7.0]

Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/managers/storage/StorageException

	at nl.evolutioncoding.AreaShop.commands.AddCommand.execute(AddCommand.java:111) ~[?:?]

	at nl.evolutioncoding.AreaShop.CommandManager.onCommand(CommandManager.java:121) ~[?:?]

	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-R0.1-SNAPSHOT]

	... 13 more

####For Sign:

[01:58:34] [Server thread/ERROR]: Could not pass event SignChangeEvent to AreaShop v2.0.2

org.bukkit.event.EventException

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]

	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-R0.1-SNAPSHOT]

	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]

	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]

	at net.minecraft.network.NetHandlerPlayServer.func_147343_a(NetHandlerPlayServer.java:2294) [nh.class:?]

	at net.minecraft.network.play.client.C12PacketUpdateSign.func_148833_a(SourceFile:48) [jn.class:?]

	at net.minecraft.network.play.client.C12PacketUpdateSign.func_148833_a(SourceFile:9) [jn.class:?]

	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]

	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]

	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]

	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]

	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]

	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]

	at java.lang.Thread.run(Thread.java:722) [?:1.7.0]

Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/managers/storage/StorageException

	at nl.evolutioncoding.AreaShop.SignChangeListener.onSignChange(SignChangeListener.java:116) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0]

	at java.lang.reflect.Method.invoke(Method.java:601) ~[?:1.7.0]

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]

	... 13 more

####Tip: i use plotshop aswell maybe it is conflictual ?

**Comment by NLthijs48** [comment]
This is caused by a mismatch of your WorldGuard and AreaShop version, simply updating to the latest AreaShop should fix the issue. The latest AreaShop does still support 1.7.9+ so that should work without problems.

Let me know if that works or if you encountered another problem.

**Comment by Tombraxis** [comment]
the first time i added the plugin it was the latest 1.7.9 version and the plugin folder wasn't creating when starting the server. Il so choose to implement an earlier version an the file created itself but now that i reimplemented the latest, whenever i do a command of areashop it says "/AreaShop or /AS and nothing happen even in the console when i write the command or on a sign

**Comment by NLthijs48** [comment]
What this means is that the plugin did not start correctly, so you need to check the log file to see what went wrong. The console (like the Multicraft console) does not show everything because often it is going too quickly for it, so checking the `/logs/latest.log` file is necessary (assuming that KCauldron has the same log location as Spigot). If you can send me the log file I can tell you what is going wrong.

**Comment by Tombraxis** [comment]
[17:22:54] [Server thread/INFO]: Tombraxis[/109.89.223.81:52542] logged in with entity id 382 at ([imperiumfinal] -30467.31581649602, 63.0, 702.8848095719881)
[17:22:54] [Server thread/INFO]: Sending mutations to player: Tombraxis
[17:22:54] [Server thread/INFO]: Send data to Tombraxis
[17:22:54] [Server thread/INFO]: Send data to Tombraxis
[17:22:54] [Server thread/INFO]: Send data to Tombraxis
[17:22:54] [Server thread/INFO]: Send data to Tombraxis
[17:22:54] [Server thread/INFO]: Send data to Tombraxis
[17:22:54] [Server thread/INFO]: Send data to Tombraxis
[17:22:54] [Server thread/INFO]: Send data to Tombraxis
[17:22:54] [Server thread/INFO]: Send data to Tombraxis
[17:22:54] [Server thread/INFO]: Send data to Tombraxis
[17:22:54] [Server thread/INFO]: Send data to Tombraxis
[17:22:54] [Server thread/INFO]: Send data to Tombraxis
[17:22:54] [Server thread/INFO]: Send data to Tombraxis
[17:22:54] [Server thread/INFO]: Send data to Tombraxis
[17:22:54] [Server thread/INFO]: Send data to Tombraxis
[17:22:54] [Server thread/INFO]: Send data to Tombraxis
[17:23:00] [Server thread/INFO]: Tombraxis issued server command: /as
[17:25:50] [Server thread/INFO]: CONSOLE: Stopping the server..[m
[17:25:50] [Server thread/INFO]: [Dynmap] Unloaded 11 components.
[17:25:50] [Server thread/INFO]: [Dynmap] Stopping map renderer...
[17:25:51] [Server thread/INFO]: [Dynmap] Saved 12 pending tile renders in world 'imperiumfinal'
[17:25:51] [Server thread/INFO]: [Dynmap] Disabled
[17:25:51] [Server thread/INFO]: Stopping server
[17:25:51] [Server thread/INFO]: [1vs1] Disabling 1vs1 v1.7.0 #220
[17:25:51] [Server thread/INFO]: [1vs1] Disconnecting from database
[17:25:51] [Server thread/INFO]: [1vs1] 1vs1 disabled!
[17:25:51] [Server thread/INFO]: [PlotShop] Disabling PlotShop v2.0.1
[17:25:51] [Server thread/INFO]: [AreaShop] Disabling AreaShop v2.1.0
[17:25:51] [Server thread/ERROR]: Error occurred while disabling AreaShop v2.1.0 (Is it up to date?)
java.lang.NullPointerException
	at nl.evolutioncoding.areashop.AreaShop.onDisable(AreaShop.java:161) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:318) ~[JavaPlugin.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:392) [JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:429) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:422) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.disablePlugins(CraftServer.java:364) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:560) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:729) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:722) [?:1.7.0]
[17:25:51] [Server thread/INFO]: [EssentialsAntiBuild] Disabling EssentialsAntiBuild v2.12.1
[17:25:51] [Server thread/INFO]: [Vault] Disabling Vault v1.5.0-b28
[17:25:51] [Server thread/INFO]: [Essentials] Payment method was disabled. No longer accepting payments.
[17:25:51] [Server thread/INFO]: [EssentialsChat] Disabling EssentialsChat vPre2.14.1.3
[17:25:51] [Server thread/INFO]: [EssentialsSpawn] Disabling EssentialsSpawn v2.12.1
[17:25:51] [Server thread/INFO]: [WGPG] Disabling WorldGuardPolygonGenerator v1.1
[17:25:51] [Server thread/INFO]: [EssentialsProtect] Disabling EssentialsProtect v2.12.1
[17:25:51] [Server thread/INFO]: [Essentials] Disabling Essentials v2.12.1
[17:25:51] [Server thread/INFO]: [Handcuffs] Disabling Handcuffs v1.3
[17:25:51] [Server thread/INFO]: [HorseProtect] Disabling HorseProtect v1.6.1
[17:25:51] [Server thread/INFO]: [WorldGuard] Disabling WorldGuard v5.8
[17:25:51] [Server thread/INFO]: [Gringotts] Disabling Gringotts v2.3
[17:25:51] [Server thread/INFO]: [Gringotts] disabled
[17:25:51] [Server thread/INFO]: [Buycraft] Disabling Buycraft v6.8
[17:25:51] [Server thread/INFO]: [Buycraft] Plugin has been disabled.
[17:25:51] [Server thread/INFO]: [VoxelSniper] Disabling VoxelSniper v5.168.9-SNAPSHOT-jnks278
[17:25:51] [Server thread/INFO]: [WorldEdit] Disabling WorldEdit v5.5.8
[17:25:51] [Server thread/INFO]: [SerialKey] Disabling SerialKey v0.2.1
[17:25:51] [Server thread/INFO]: [GroupManager] Disabling GroupManager vPre2.14.1.3 FINAL (Phoenix)
[17:25:51] [Server thread/INFO]: GroupManager - INFO - Scheduled Data Saving is disabled!
[17:25:51] [Server thread/INFO]: GroupManager version Pre2.14.1.3 FINAL (Phoenix) is disabled!
[17:25:51] [Server thread/INFO]: [MultiWorld] Disabling MultiWorld v5.1.1
[17:25:51] [Server thread/INFO]: [MultiWorld] Disabled.
[17:25:51] [Server thread/INFO]: Saving players
[17:25:51] [Server thread/INFO]: Tombraxis lost connection: Server closed
[17:25:51] [Server thread/INFO]: Tombraxis left the game.
[17:25:51] [Server thread/INFO]: Saving worlds
[17:25:51] [Server thread/INFO]: Saving chunks for level 'imperiumfinal'/Overworld
[17:25:52] [Server thread/INFO]: Saving chunks for level 'DIM1'/The End
[17:25:52] [Server thread/INFO]: Saving chunks for level 'DIM-1'/Nether
[17:25:52] [Server thread/INFO]: Saving chunks for level 'ancienne'/Overworld
[17:25:52] [Server thread/INFO]: Saving chunks for level 'imperium'/Overworld
[17:25:52] [Server thread/INFO]: Saving chunks for level 'imperiumfinal_nether'/Nether
[17:25:52] [Server thread/INFO]: Saving chunks for level 'imperiumfinal_the_end'/The End
[17:25:52] [Server thread/INFO]: Unloading dimension 0
[17:25:52] [Server thread/INFO]: Unloading dimension -1
[17:25:52] [Server thread/INFO]: Unloading dimension 1
[17:25:52] [Server thread/INFO]: Unloading dimension 8
[17:25:52] [Server thread/INFO]: Unloading dimension 7
[17:25:52] [Server thread/INFO]: Unloading dimension 6
[17:25:52] [Server thread/INFO]: Unloading dimension 2
[17:25:52] [Server thread/INFO]: Applying holder lookups
[17:25:52] [Server thread/INFO]: Holder lookups applied
[17:25:52] [Server thread/INFO]: Stopped Voice Server.

**Comment by NLthijs48** [comment]
You are still running AreaShop V2.1.0 instead of the latest version (V2.4.0), this is causing the problem. Upgrade to the [latest AreaShop](https://github.com/NLthijs48/AreaShop/releases).

>[15:38:05] [Server thread/INFO]: [AreaShop] Enabling AreaShop v2.1.0
