### ISSUE TITLE
Exception when restore region by "schematicProfile" settings

### ISSUE THREAD

**Issue by k-jiang** [NLthijs48/AreaShop#272]
#### Steps to reproduce (for bugs)

1. /as setrestore region-id true a-schematicProfile-name
2. /as rent region-id
3. 
```
[13:14:40 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'as' in plugin AreaShop v2.4.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-survival.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-survival.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot-survival.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1337) [spigot-survival.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1172) [spigot-survival.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-survival.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-survival.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-survival.jar:git-Spigot-6f7aabf-c8ff651]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-survival.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-survival.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-survival.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-survival.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-survival.jar:git-Spigot-6f7aabf-c8ff651]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at me.wiefferink.areashop.regions.GeneralRegion.handleSchematicEvent(GeneralRegion.java:1740) ~[?:?]
        at me.wiefferink.areashop.regions.RentRegion.unRent(RentRegion.java:688) ~[?:?]
        at me.wiefferink.areashop.commands.UnrentCommand.execute(UnrentCommand.java:84) ~[?:?]
        at me.wiefferink.areashop.managers.CommandManager.onCommand(CommandManager.java:112) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-survival.jar:git-Spigot-6f7aabf-c8ff651]
        ... 15 more
```

4. 

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.11.2 build 1129
* AreaShop version: 2.4.0
* WorldEdit version: 6.1.5
* WorldGuard version: 6.2.1 build1696
* Vault version: 

#### Your config files (for bugs)

It also happened to groups.yml method you have mentioned in #197 , so I just post the config here:
default.yml
`enableRestore: false`
groups.yml
```
xinshoucun-shop:
  name: xinshoucun-shop
  priority: 0
  general:
    schematicProfile: 'xinshoucun-shop'
    enableRestore: true
  regions:
  - pri-shop-01
  - pri-shop-02
  - pri-shop-03
  - pri-shop-04
```

**Comment by k-jiang** [comment]
default.yml:
```
  enableRestore: false
  schematicProfile:
    created:
      save: '%type%-%region%'
      restore: ''
    deleted:
      save: ''
      restore: '%type%-%region%'
    rented:
      save: '%type%-%region%'
      restore: ''
    unrented:
      save: ''
      restore: '%type%-%region%'
    bought:
      save: '%type%-%region%'
      restore: ''
    sold:
      save: ''
      restore: '%type%-%region%'
    resell:
      save: ''
      restore: ''
```

**Comment by NLthijs48** [comment]
Remove the line with `schematicProfile: 'xinshoucun-shop'` from the `groups.yml` file, you have already set the profile in `default.yml` so you should not set it to something else in the group. The error is a bug caused by setting a profile that does not actually exist (which I'll fix).

**Comment by k-jiang** [comment]
I used to think settings on groups.yml will override what default.yml or config.yml said...

**Comment by NLthijs48** [comment]
Yes they do indeed, but if you only want the schematicprofile to be for a group then you either need to move the complete profile to the `groups.yml` file or set it in the config (this is the old way of doing things though).

**Comment by k-jiang** [comment]
Sorry what do you mean by "move the complete profile to the `groups.yml` file or set it in the config". Could you give me some examples, please?

**Comment by NLthijs48** [comment]
Use it like this in the `groups.yml` file:
```yaml
xinshoucun-shop:
  name: xinshoucun-shop
  priority: 0
  general:
    schematicProfile:
      created:
        save: '%type%-%region%'
        restore: ''
      deleted:
        save: ''
        restore: '%type%-%region%'
      rented:
        save: '%type%-%region%'
        restore: ''
      unrented:
        save: ''
        restore: '%type%-%region%'
      bought:
        save: '%type%-%region%'
        restore: ''
      sold:
        save: ''
        restore: '%type%-%region%'
      resell:
        save: ''
        restore: ''
    enableRestore: true
  regions:
  - pri-shop-01
  - pri-shop-02
  - pri-shop-03
  - pri-shop-04
```

So instead of providing a name of a profile, you put all settings of the profile itself there. Let me know if that explains it.

**Comment by k-jiang** [comment]
Thank you! That makes more senses now. And it would be great if you can specified this in the wiki so ppl (like me) won't get confused.

Just curious, if the "general" section can have all the settings from default.yml, does it means I can set other things like rent.maxRentTime as well?

**Comment by NLthijs48** [comment]
Yeah the wiki still needs to be updated to the new config layout, I'm planning on doing that but it takes a lot of time to write documentation pages like that.
