### ISSUE TITLE
everybody can interact with entrance door of my As region when rented

### ISSUE THREAD

**Issue by Tombraxis** [NLthijs48/AreaShop#284]
When an area is rented, everybody can interact with the entrance door. When i use the flag "use deny" then nobody even the renter can't interact. 

Only the renter and the owner should be able to use the door

**Comment by Tombraxis** [comment]
i suspect that areashop dont put the renter into members group. therefore, the plugin dont recognise renters from non renters

**Comment by Tombraxis** [comment]
i also have this in my console i don't know what it means but i'm pretty sure this is related Could not pass event UpdateRegionEvent to AreaShop v2.4.0

org.bukkit.event.EventException

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]

	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-R0.1-SNAPSHOT]

	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]

	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]

	at me.wiefferink.areashop.regions.GeneralRegion.update(GeneralRegion.java:219) [AreaShop(4).jar:?]

	at me.wiefferink.areashop.regions.GeneralRegion.notifyAndUpdate(GeneralRegion.java:228) [AreaShop(4).jar:?]

	at me.wiefferink.areashop.regions.RentRegion.unRent(RentRegion.java:702) [AreaShop(4).jar:?]

	at me.wiefferink.areashop.commands.UnrentCommand.execute(UnrentCommand.java:84) [AreaShop(4).jar:?]

	at me.wiefferink.areashop.managers.CommandManager.onCommand(CommandManager.java:112) [AreaShop(4).jar:?]

	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:1.7.10-R0.1-SNAPSHOT]

	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [SimpleCommandMap.class:1.7.10-R0.1-SNAPSHOT]

	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]

	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]

	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]

	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]

	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]

	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]

	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]

	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]

	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]

	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]

	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]

	at java.lang.Thread.run(Thread.java:722) [?:1.7.0]

Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.domains.DefaultDomain.removeAll()V

	at me.wiefferink.areashop.handlers.WorldGuardHandler5.setMembers(WorldGuardHandler5.java:65) ~[?:?]

	at me.wiefferink.areashop.features.WorldGuardRegionFlagsFeature.updateRegionFlags(WorldGuardRegionFlagsFeature.java:81) ~[?:?]

	at me.wiefferink.areashop.features.WorldGuardRegionFlagsFeature.updateRegionFlags(WorldGuardRegionFlagsFeature.java:43) ~[?:?]

	at me.wiefferink.areashop.features.WorldGuardRegionFlagsFeature.regionUpdate(WorldGuardRegionFlagsFeature.java:22) ~[?:?]

	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0]

	at java.lang.reflect.Method.invoke(Method.java:601) ~[?:1.7.0]

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]

	... 22 more

**Comment by Tombraxis** [comment]
Problem solved, outdated worldguard version

**Comment by NLthijs48** [comment]
Good that you solved it, AreaShop does support WorldGuard 5, but only if it is 5.9 or higher, which you probably did not have.

Let me know if you encounter any other problems.
