### ISSUE TITLE
build 146 plugin.yml issue

### ISSUE THREAD

**Issue by frizzbee30** [NLthijs48/AreaShop#302]
Hi, just for info, getting an error int he latest dev build  :)

[15:57:00] [Server thread/ERROR]: Could not load 'plugins\AreaShop.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more
[15:57:11] [Server thread/ERROR]: Could not load 'plugins\HyperDrive-Program-v1.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more

**Comment by NLthijs48** [comment]
It definitely does contain a plugin.yml file, try unzipping it. Did you maybe change the jar file while the server was running? Or does the server not have permissions to read the file?

You also have another plugin with the same problem below it, maybe there is something wrong with the server?

Let me know if you have solved it or not.

**Comment by frizzbee30** [comment]
Hi, I re-downloaded the build and got a different filesize which has now loaded ok, so not quite sure what happened as i don't normally have any issues.

So all sorted, thanks for the quick response :)

**Comment by frizzbee30** [comment]
(other plugin was actually a standalone which isn't meant to load, didn't realise I copied it in :)  )

**Comment by NLthijs48** [comment]
Okey, probably your browser did not download the complete file, which does happen sometimes, good that it works now.
