### ISSUE TITLE
please upd plugin for new WorldEdit WorldGuard and 1.12 Minecraft. THANKS

### ISSUE THREAD

**Issue by BabelSolea** [NLthijs48/AreaShop#323]
`[17:11:22 ERROR]: Could not load 'plugins/AreaShop.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Vault
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [SW02spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:302) [SW02spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [SW02spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [SW02spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]`

**Comment by BabelSolea** [comment]
my bad i forget about Vault =(

**Comment by NLthijs48** [comment]
That is indeed just Vault missing, let me know if you have any other problems/questions
