### ISSUE TITLE
Not too sure what I did wrong

### ISSUE THREAD

**Issue by RainOfPain125** [NLthijs48/AreaShop#381]
#### Current behavior

Players can not place blocks inside their shop (probably just me being stupid)

#### Steps to reproduce (for bugs)

1. Create Region
2. Create AreaShop
3. Rent AreaShop
4. Can't place anything in AreaShop

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): Paper Spigot
* Server version: git-Paper-1288
* AreaShop version: 2.4.0
* WorldEdit version: 6.1.8-SNAPSHOT;cd4729f
* WorldGuard version: 6.2.1;84bc322
* Vault version: 1.6.1

**Comment by NLthijs48** [comment]
Do you have a `build: deny` flag on regions that cover the same location or the `__global__` region? If so, remove that flag. Normal regions don't need the `build` flag, they are protected already, and the `__global__` region should have `passthrough: deny` instead.

Let me know if that works for you.

**Comment by RainOfPain125** [comment]
I have a region that contains all the player shops (but I haven't fiddled with its flags) because I don't want players to destroy the shops themselves or the shops around them. __global__ hasn't been touched either

**Comment by RainOfPain125** [comment]
.-.

**Comment by NLthijs48** [comment]
Do you get a message when you try to place a block in the region? If you get a message like 'Hey! You cannot do that...' it is WorldGuard that is the problem. If you do not get a message, it is something else causing it. Maybe you have `spawn-protection` in the `server.properties` file not set to `0`? Or maybe another protection plugins blocks it.

If it is WorldGuard though, please send me screenshots of `/region info <region>` for all regions that are in the location of the AreaShop region, `__global__` and the AreaShop region itself.

**Comment by RainOfPain125** [comment]
It says "Hey sorry! But you can't place that here"

![2018-01-18_12 12 21](https://user-images.githubusercontent.com/33137905/35111415-34c42cce-fc49-11e7-9f7b-a6aaae3a9259.png)
![2018-01-18_12 14 31](https://user-images.githubusercontent.com/33137905/35111416-34d41f58-fc49-11e7-9de9-763d3deeb5be.png)

**Comment by NLthijs48** [comment]
The flags on your screenshot are correct, they should give you permissions to build. Are there any other regions at the same spot? You can test it by using `/rg info`, which either will tell you a list of regions or show the information if there is just one.

If there is no other region I'm really confused, maybe you have added special WorldGuard permissions? I could join your server to check it out.

**Comment by RainOfPain125** [comment]
Theres one more region that highlights the current entire area of our AreaShops named pshop, but it only has one flag (mob-spawning deny)

I haven't touched world guard, I only installed it because a friend said so

If you wanna join and get OP, mess around with it you can

https://discord.gg/pD3bCyS

**Comment by RainOfPain125** [comment]
This error is in console on boot now

[16:22:24 INFO]: [AreaShop] Enabling AreaShop v2.4.0
[16:22:25 ERROR]: Cannot load configuration from stream
org.bukkit.configuration.InvalidConfigurationException: unacceptable code point ' ' (0x0) special characters are not allowed
in "'string'", position 0
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[patched_1.12.2.jar:git-Paper-1305]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[patched_1.12.2.jar:git-Paper-1305]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:206) [patched_1.12.2.jar:git-Paper-1305]
        at me.wiefferink.areashop.managers.FileManager.loadRegionFiles(FileManager.java:879) [AreaShop.jar:?]
        at me.wiefferink.areashop.managers.FileManager.loadFiles(FileManager.java:723) [AreaShop.jar:?]
        at me.wiefferink.areashop.AreaShop.onEnable(AreaShop.java:264) [AreaShop.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [patched_1.12.2.jar:git-Paper-1305]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1305]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1305]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:383) [patched_1.12.2.jar:git-Paper-1305]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:332) [patched_1.12.2.jar:git-Paper-1305]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1305]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1305]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1305]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1305]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1305]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
        at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:67) ~[patched_1.12.2.jar:git-Paper-1305]
        at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:45) ~[patched_1.12.2.jar:git-Paper-1305]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[patched_1.12.2.jar:git-Paper-1305]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) ~[patched_1.12.2.jar:git-Paper-1305]
        ... 16 more
[16:22:25 WARN]: [AreaShop] Region file 'shop1.yml' is empty, check for errors in the log.

**Comment by NLthijs48** [comment]
The `plugins/AreaShop/regions/shop1.yml` file is corrupt, could you show me what is inside? It might be easiest to remove this region from AreaShop and add it again.

I also joined your Discord, are you `[RA|HHR-5] Rain`?
