### ISSUE TITLE
Error in Log

### ISSUE THREAD

**Issue by HomeLandingsDE** [NLthijs48/AreaShop#392]
Can you tell me what i can do with this error?

[18:17:33] [Server thread/WARN]: [AreaShop] Command execution failed, command=areashop buy gs_18, error=Unhandled exception executing command 'areashop' in plugin AreaShop v2.4.0, stacktrace:
[18:17:33] [Server thread/WARN]: [AreaShop] org.bukkit.command.CommandException: Unhandled exception executing command 'areashop' in plugin AreaShop v2.4.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:649)
	at me.wiefferink.areashop.regions.GeneralRegion.runCommands(GeneralRegion.java:1778)
	at me.wiefferink.areashop.features.SignsFeature$RegionSign.runSignCommands(SignsFeature.java:340)
	at me.wiefferink.areashop.listeners.SignClickListener.onSignClick(SignClickListener.java:60)
	at sun.reflect.GeneratedMethodAccessor329.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235)
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458)
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951)
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.has(Economy_Craftconomy3.java:283)
	at net.milkbowl.vault.economy.AbstractEconomy.has(AbstractEconomy.java:35)
	at me.wiefferink.areashop.regions.BuyRegion.buy(BuyRegion.java:321)
	at me.wiefferink.areashop.commands.BuyCommand.execute(BuyCommand.java:47)
	at me.wiefferink.areashop.managers.CommandManager.onCommand(CommandManager.java:112)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	... 26 more

[18:17:33] [Server thread/WARN]: [AreaShop] --- End of stacktrace ---

**Comment by NLthijs48** [comment]
It looks like your Economy plugin (Craftconomy3) has a problem. When a player is buying a region AreaShop asks the economy plugin if the player has the required money, and Craftconomy3 is crashing because of that.

You could check if Craftconomy has a new version, which might fix the problem.

Let me know if that works.

**Comment by HomeLandingsDE** [comment]
but all Areas to buy are for free

**Comment by NLthijs48** [comment]
AreaShop will currently still check if the player has `$0` though, which should simply return a positive result.

Did you check if you have the latest Craftconomy and Vault?
