### ISSUE TITLE
1.13 Version

### ISSUE THREAD

**Issue by KlenerTeufel96** [NLthijs48/AreaShop#411]
I only want to ask if there will be a 1.13 Version ^^
Best Regards 
KlenerTeufel96

**Comment by seema84** [comment]
pretty shure it will

**Comment by NLthijs48** [comment]
I'm working on an update.

WorldGuard and WorldEdit made a lot of changes so I need to change more things than I initially hoped for. I'm about halfway there though, just a couple of more issues to solve before I can start testing if it all works as expected. After I have done some initial testing of the changes I will push the new code so that you guys can download a development build for testing.

WorldGuard and WorldEdit are both working on a version 7 in a separate branch called `string-ids`, probably they will release this new version in the following weeks.

**Comment by NLthijs48** [comment]
Done with the changes, a build can soon be found on [http://wiefferink.me:8080/job/AreaShop](http://wiefferink.me:8080/job/AreaShop), number 243 or higher has 1.13 support.

I only tested some things using the console, my Minecraft installation is broken currently. Soon I'll test it further.

**NOTE: this is an untested development build, do not run this on your live server!**

**Comment by GothkittyGirl** [comment]
well i found that you cant just do /as sell you have to add  the region name as well

**Comment by NLthijs48** [comment]
Any error in the console/log? It looks like a bug

**Comment by GothkittyGirl** [comment]
[06:35:02] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'as' in plugin AreaShop v2.4.0#244
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:693) ~[spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(Lorg/bukkit/World;)Lcom/sk89q/worldguard/protection/managers/RegionManager;
	at me.wiefferink.areashop.handlers.WorldGuardHandler6.getApplicableRegionsSet(WorldGuardHandler6.java:38) ~[?:?]
	at me.wiefferink.areashop.tools.Utils.getImportantRegions(Utils.java:458) ~[?:?]
	at me.wiefferink.areashop.tools.Utils.getImportantBuyRegions(Utils.java:433) ~[?:?]
	at me.wiefferink.areashop.commands.SellCommand.execute(SellCommand.java:54) ~[?:?]
	at me.wiefferink.areashop.managers.CommandManager.onCommand(CommandManager.java:142) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	... 15 more

**Comment by GothkittyGirl** [comment]
that was when i tryed to /as sell without the region name

**Comment by NLthijs48** [comment]
@GothkittyGirl what does `/version worldguard` show? It looks like you still have the wrong one.

**Comment by GothkittyGirl** [comment]
should be latest one 7.0.0-SNAPSHOT;1733-8161fd0

**Comment by NLthijs48** [comment]
That is good, are you sure you restarted your sever? I'll take a look if it works for me this evening to verify I implemented it correctly

**Comment by GothkittyGirl** [comment]
yes ive restarted it to make it was in correctly only time i get a error is when i try to sell/unrent and region without adding the region name. even while standing in it it still give "an error has occured" msg and console errors

**Comment by Zethrus** [comment]
I had an issue similar to what @GothkittyGirl had. Although, the command was different; /as setprice when standing in the region.

**Comment by NLthijs48** [comment]
The latest development build fixes the issue @GothkittyGirl @Zethrus.
