### ISSUE TITLE
same error newest versions

### ISSUE THREAD

**Issue by GothkittyGirl** [NLthijs48/AreaShop#415]
**Current behavior**
<[11:07:51] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'as' in plugin AreaShop v2.4.0#244
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:693) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(Lorg/bukkit/World;)Lcom/sk89q/worldguard/protection/managers/RegionManager;
	at me.wiefferink.areashop.handlers.WorldGuardHandler6.getApplicableRegionsSet(WorldGuardHandler6.java:38) ~[?:?]
	at me.wiefferink.areashop.tools.Utils.getImportantRegions(Utils.java:458) ~[?:?]
	at me.wiefferink.areashop.tools.Utils.getImportantBuyRegions(Utils.java:433) ~[?:?]
	at me.wiefferink.areashop.commands.SellCommand.execute(SellCommand.java:54) ~[?:?]
	at me.wiefferink.areashop.managers.CommandManager.onCommand(CommandManager.java:142) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	... 15 more
>

**Expected behavior**
[11:07:51] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'as' in plugin AreaShop v2.4.0#244
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:693) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-69774b3-671581e]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(Lorg/bukkit/World;)Lcom/sk89q/worldguard/protection/managers/RegionManager;
	at me.wiefferink.areashop.handlers.WorldGuardHandler6.getApplicableRegionsSet(WorldGuardHandler6.java:38) ~[?:?]
	at me.wiefferink.areashop.tools.Utils.getImportantRegions(Utils.java:458) ~[?:?]
	at me.wiefferink.areashop.tools.Utils.getImportantBuyRegions(Utils.java:433) ~[?:?]
	at me.wiefferink.areashop.commands.SellCommand.execute(SellCommand.java:54) ~[?:?]
	at me.wiefferink.areashop.managers.CommandManager.onCommand(CommandManager.java:142) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.jar:git-Spigot-69774b3-671581e]
	... 15 more

**Steps to reproduce**

1. updated everything
2. restart
3. /as sell
4. an internal error occurred

**Your environment**

* Server platform (Bukkit, Spigot, etc.): 
* Server version: git-spigot-69774b3-671581e (mc: 1.13) (implementing api version 1.13-r0.1-snapshot
* AreaShop version:  build #244
* WorldEdit version: 7.0.0-snapshop;3812-1d9546f
* WorldGuard version: 7.0.0-snapshop;1729-91c03c5
* Vault version: v1.6.1

**Your config files**

**Comment by NLthijs48** [comment]
You need to update WorldGuard to a development build from the string-ids branch, see [this comment](https://github.com/NLthijs48/AreaShop/issues/411#issuecomment-410482273).
