### ISSUE TITLE
Warning spaming console

### ISSUE THREAD

**Issue by Ectabro** [NLthijs48/AreaShop#422]
Hello !

I have an exception spaming my console, but areashop seems to work perfectly..

This is the exception:

[15:10:57 WARN]: [AreaShop] Task #4518 for AreaShop v2.4.0#245 generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldedit.extent.clipboard.io.BuiltInClipboardFormat.values()[Lcom/sk89q/worldedit/extent/clipboard/io/BuiltInClipboardFormat;
        at me.wiefferink.areashop.handlers.WorldEditHandler7.restoreRegionBlocks(WorldEditHandler7.java:66) ~[?:?]
        at me.wiefferink.areashop.regions.GeneralRegion.restoreRegionBlocks(GeneralRegion.java:771) ~[?:?]
        at me.wiefferink.areashop.regions.GeneralRegion.handleSchematicEvent(GeneralRegion.java:1409) ~[?:?]
        at me.wiefferink.areashop.regions.RentRegion.unRent(RentRegion.java:711) ~[?:?]
        at me.wiefferink.areashop.regions.RentRegion.checkExpiration(RentRegion.java:358) ~[?:?]
        at me.wiefferink.areashop.shaded.bukkitdo.Do$9.run(Do.java:227) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:877) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Steps to reproduce**

1. 
2. 
3. 
4. 

**Your environment**

* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.13
* AreaShop version: 2.4.0#245
* WorldEdit version: WorldEdit - Version: unspecified- Author(s): Empire92 - Status: Enabled
* WorldGuard version: 7.0.0-SNAPSHOT;febd212
* Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}

**Your config files**

**Comment by doitliketyler** [comment]
+1

https://pastebin.com/4euwVzts

**Comment by Sprungente** [comment]
Schem don't working fine with areashop and worldedit/FAWE have issues with it too.

**Comment by NLthijs48** [comment]
Does the latest developer build fix it?
http://wiefferink.me:8080/job/AreaShop/

**Comment by NLthijs48** [comment]
Compatibility with FAWE will be tracked further in this issue https://github.com/NLthijs48/AreaShop/issues/436, I'll close this one.
