### ISSUE TITLE
Could not pass update region

### ISSUE THREAD

**Issue by 0xC1A551C** [NLthijs48/AreaShop#434]
**Current behavior**
While adding signs some update some dont

**Expected behavior**
All rights should update to [rent] or [sale] when added.

**Steps to reproduce**

1. create a shop
2.  create a sign to show shop with [as] shopname
3. 
4. 

**Your environment**

* Server platform (Bukkit, Spigot, etc.): 
* Server version:  1.13.1
* AreaShop version:  latest of time of writing
* WorldEdit version: snapshop
* WorldGuard version:  fawe version
* Vault version: latest

[03:10:39 ERROR]: Could not pass event UpdateRegionEvent to AreaShop v2.4.0#249
org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.1.jar:git-Paper-373]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.1.jar:git-Paper-373]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.1.jar:git-Paper-373]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.1.jar:git-Paper-373]
at me.wiefferink.areashop.regions.GeneralRegion.update(GeneralRegion.java:276) ~[?:?]
at me.wiefferink.areashop.shaded.bukkitdo.Do$1.run(Do.java:34) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.1.jar:git-Paper-373]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.1.jar:git-Paper-373]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.1.jar:git-Paper-373]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-373]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-373]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-373]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
at me.wiefferink.areashop.features.signs.RegionSign.update(RegionSign.java:157) ~[?:?]
at me.wiefferink.areashop.features.signs.SignsFeature.update(SignsFeature.java:504) ~[?:?]
at me.wiefferink.areashop.features.signs.SignsFeature.regionUpdate(SignsFeature.java:484) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor998.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.1.jar:git-Paper-373]
... 12 more

**Comment by NLthijs48** [comment]
I think FAWE is causing trouble, others have reported it does not work with AreaShop somehow.

I still need to find a way to fix that.

**Comment by NLthijs48** [comment]
This bug has been fixed, it is the same one as #440, [development builds](http://wiefferink.me:8080/job/AreaShop/) contain the fix.
