### ISSUE TITLE
Cannot unrent

### ISSUE THREAD

**Issue by 0xC1A551C** [NLthijs48/AreaShop#435]
using the latest dev buil when trying to /unrent a region (as op)

[04:19:05 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'as' in plugin AreaShop v2.4.0#249
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.1.jar:git-Paper-373]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.1.jar:git-Paper-373]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:729) ~[patched_1.13.1.jar:git-Paper-373]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1743) ~[patched_1.13.1.jar:git-Paper-373]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1547) ~[patched_1.13.1.jar:git-Paper-373]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.1.jar:git-Paper-373]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.1.jar:git-Paper-373]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.1.jar:git-Paper-373]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.1.jar:git-Paper-373]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.1.jar:git-Paper-373]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-373]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-373]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-373]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.extent.clipboard.io.BuiltInClipboardFormat.values()[Lcom/sk89q/worldedit/extent/clipboard/io/BuiltInClipboardFormat;
at me.wiefferink.areashop.handlers.WorldEditHandler7.restoreRegionBlocks(WorldEditHandler7.java:66) ~[?:?]
at me.wiefferink.areashop.regions.GeneralRegion.restoreRegionBlocks(GeneralRegion.java:771) ~[?:?]
at me.wiefferink.areashop.regions.GeneralRegion.handleSchematicEvent(GeneralRegion.java:1409) ~[?:?]
at me.wiefferink.areashop.regions.RentRegion.unRent(RentRegion.java:711) ~[?:?]
at me.wiefferink.areashop.commands.UnrentCommand.execute(UnrentCommand.java:79) ~[?:?]
at me.wiefferink.areashop.managers.CommandManager.onCommand(CommandManager.java:142) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.1.jar:git-Paper-373]
... 15 more

**Comment by Sprungente** [comment]
try the lastest devbuild

**Comment by NLthijs48** [comment]
Update to the latest release here on Github or of Spigot
