### ISSUE TITLE
Sign update bug

### ISSUE THREAD

**Issue by andfont** [NLthijs48/AreaShop#440]
**Current behavior**
When you start playing and do things, break stone or normal activities suddenly this error comes out that does not let you play and the server stops!

**Expected behavior**
Do not leave this message

**Steps to reproduce**

1. Regenerate some terrain
2. Play normally
3. Management with the worldedit, copy paste etc

**Your environment**

* Server platform (Bukkit, Spigot, etc.): 
* Server version: MC 1.13.1 Spigot
* AreaShop version: 2.5.0
* WorldEdit version: 7.0.0 Dist
* WorldGuard version: 7.0.0 Distri
* Vault version: 1.7.1

Error:
[11:46:44] [Server thread/WARN]: [AreaShop] Task #160362 for AreaShop v2.5.0 generated an exception
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
	at me.wiefferink.areashop.features.signs.RegionSign.update(RegionSign.java:157) ~[?:?]
	at me.wiefferink.areashop.shaded.bukkitdo.Do$9.run(Do.java:227) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[11:46:44] [Server thread/WARN]: [AreaShop] Task #160362 for AreaShop v2.5.0 generated an exception
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
	at me.wiefferink.areashop.features.signs.RegionSign.update(RegionSign.java:157) ~[?:?]
	at me.wiefferink.areashop.shaded.bukkitdo.Do$9.run(Do.java:227) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by NLthijs48** [comment]
I cannot reproduce your issue, could you send me a `.zip` of the `/plugins/AreaShop` folder?
Which plugins are your using on your servers? Do you maybe use FastAsyncWorldEdit or AsyncWorldEdit?

**Comment by andfont** [comment]
http://superabf.net:9123/resabf/areashop.zip
if you have the file, I have been able to verify that I think that when using the world edit or playing normally breaking blocks when you want, the error jumps. regards

**Comment by andfont** [comment]
http://superabf.net:9123/resabf/areashop.zip
if you have the file, I have been able to verify that I think that when using the world edit or playing normally breaking blocks when you want, the error jumps. regards

**Comment by andfont** [comment]
http://superabf.net:9123/resabf/areashop.zip
if you have the file, I have been able to verify that I think that when using the world edit or playing normally breaking blocks when you want, the error jumps. regards

**Comment by andfont** [comment]
http://superabf.net:9123/resabf/areashop.zip
if you have the file, I have been able to verify that I think that when using the world edit or playing normally breaking blocks when you want, the error jumps. regards

**Comment by NLthijs48** [comment]
Thanks for your information, I found a way to fix this issue, when I have an update ready I'll post an update here.

**Comment by andfont** [comment]
Thanks to you for such a good job !, I will wait for the update thank you very much xD

**Comment by NLthijs48** [comment]
This bug has been fixed, a development build is available on http://wiefferink.me:8080/job/AreaShop/, let me know if you have any trouble running it!
