### ISSUE TITLE
Support async Vault requests (LuckPerms support)

### ISSUE THREAD

**Issue by Wolfbros** [NLthijs48/AreaShop#441]
#### Current behavior
[Server thread/WARN]: [AreaShop] Task #3027 for AreaShop v2.5.0 generated an exception
java.lang.RuntimeException: The operation to load user data for 'UUID' was cancelled by LuckPerms. This is NOT a bug. 
The lookup request was made on the main server thread. It is not safe to execute a request to 
load username data from the database in this context. 
If you are a plugin author, please consider making your request asynchronously. 
Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true 
in the LP config, but should consider the consequences (lag) before doing so.
	at me.lucko.luckperms.bukkit.vault.VaultPermissionHook.lookupUser(VaultPermissionHook.java:135) ~[?:?]
	at me.lucko.luckperms.bukkit.vault.VaultPermissionHook.userHasPermission(VaultPermissionHook.java:161) ~[?:?]
	at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.playerHas(AbstractVaultPermission.java:154) ~[?:?]
	at me.wiefferink.areashop.AreaShop.hasPermission(AreaShop.java:558) ~[?:?]
	at me.wiefferink.areashop.regions.RentRegion.rent(RentRegion.java:438) ~[?:?]
	at me.wiefferink.areashop.regions.RentRegion.extend(RentRegion.java:424) ~[?:?]
	at me.wiefferink.areashop.regions.RentRegion.checkExpiration(RentRegion.java:351) ~[?:?]
	at me.wiefferink.areashop.shaded.bukkitdo.Do$9.run(Do.java:227) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-642f6d2-fbe3046]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

#### New behavior

Maybe integrate LuckPerms api

#### Steps to reproduce (for bugs)

1. rent a region
2. go offline and wait for auto extend

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version:  1.12.2 (latest)
* AreaShop version:  2.5.0
* WorldEdit version: 6.1.7
* WorldGuard version:  6.2.1
* Vault version: 1.6.7
* LuckPerms: 4.3.9

#### Your config files (for bugs)
default.yml change: autoExtend: true

**Comment by NLthijs48** [comment]
I have spoken with the author of LuckPerms, we agree that the Vault api is not really made with async calls in mind, and therefore it is hard for LuckPerms to have good performance.

I'll see if I can change a couple of things in AreaShop to prevent the warning, for now you can safely ignore it (AreaShop should not cause this warning often, and therefore not impact performance in a noticeable way for now).

**Comment by Wolfbros** [comment]
Thanks for the quick response.

**Comment by mibby** [comment]
@NLthijs48 Any possibilities on looking into this issue further? For me this error is spamming repeatedly for every single one of my rent regions.

AreaShops dev 284
LuckPerms dev 870

2036 errors since last restart ~4 hours ago.
```
[09:00:51] [Server thread/ERROR]: [AreaShop] Do.forAll() iteration failed for object: South-2-6 (me.wiefferink.areashop.regions.RentRegion)
java.lang.RuntimeException: The operation to load user data for 'uuid' was cancelled by LuckPerms. This is NOT a bug. 
The lookup request was made on the main server thread. It is not safe to execute a request to 
load data for offline players from the database in this context. 
If you are a plugin author, please consider making your request asynchronously. 
Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true 
in the LP config, but should consider the consequences (lag) before doing so.
	at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.lookupUser(LuckPermsVaultPermission.java:143) ~[?:?]
	at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.userHasPermission(LuckPermsVaultPermission.java:169) ~[?:?]
	at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.playerHas(AbstractVaultPermission.java:154) ~[?:?]
	at me.wiefferink.areashop.AreaShop.hasPermission(AreaShop.java:620) ~[?:?]
	at me.wiefferink.areashop.regions.RentRegion.rent(RentRegion.java:437) ~[?:?]
	at me.wiefferink.areashop.regions.RentRegion.extend(RentRegion.java:422) ~[?:?]
	at me.wiefferink.areashop.regions.RentRegion.checkExpiration(RentRegion.java:350) ~[?:?]
	at me.wiefferink.areashop.shaded.bukkitdo.Do$9.run(Do.java:230) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-525]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

**Comment by NLthijs48** [comment]
> Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true
Do that and it will not spam the log anymore.

This actually is an issue in LuckPerms, which I might be able to work around but has a lot of impact on the AreaShop code, possibly breaking the integration with other permissions plugins.

**Comment by mibby** [comment]
How significant of a performance impact is expected when enable unsafe/offline lookups for regions renewals?

Would it be something @lucko could possibly optimize in LuckPerms?

**Comment by lucko** [comment]
It's not something I can optimize.

Requesting data for offline players will result in database lookups, which are subject to the speed of the network / database server. The **only** way to avoid this is for plugins to make their requests asynchronously.

Yes, you can enable `vault-unsafe-lookups` - but the "unsafe" bit is not an exaggeration. If for example, there is a 25 millisecond ping delay between your Minecraft server and database, the game will pause (lag) for at least half of a tick every time AreaShop makes a lookup. Your players will most definitely notice this.

> This actually is an issue in LuckPerms

It's not - and the warning message makes that blatantly clear.

**Comment by mibby** [comment]
Thanks for the info lucko! I suppose it's on you @NLthijs48 to make AreaShop lookup request asynchronous.

**Comment by NLthijs48** [comment]
@lucko 
Sorry, my comment "This actually is an issue in LuckPerms" is wrong, in my earlier comments above I already explained the issue in more detail.

The root problem is that the Vault API is originally designed to be called on the main thread. That is why AreaShop started with calling those functions on the main thread, like their documentation suggests. Nowadays there are however economy and permission plugins that use a database (like LuckPerms), which can have a higher latency, which is really bad when used on the main thread.

So you would say, just call the Vault from another thread, but that means major code restructure and potentially breaking the compatibility with other permission and economy plugins, which expect to be called from the main thread. That is why this issue is hard to solve, and won't be done quickly.

My ultimate goal is getting AreaShop ready to use a database as well, so that would also need moving commands to another thread, but that is an even bigger project.

The actual performance impact this causes is really minimal, currently the only reason AreaShop asks for permissions of an offline player (which leads to the unsafe lookup in the stacktrace above) is when you have `autoExtend` enabled in `default.yml` to automatically extend a rental when the rent has ran out.
Assuming that you have a reasonable rental time of a week or so, this will not happen often. I guess LuckPerms just returns `false` when unsafe lookups are disabled, so that would mean automatic extending of regions will not work.

As a start I could just fix the case above, and request the permission for that from another thread.

**Comment by lucko** [comment]
LuckPerms throws an exception when unsafe lookups are disabled.
