### ISSUE TITLE
Areashop 2.5.0 failed to reset a region while runing AsyncWorldEdit and starts spamming.

### ISSUE THREAD

**Issue by Sandukhan** [NLthijs48/AreaShop#444]
Hi,
Today i tested the new version of Areashop for 1.13. and after serverstart areashop had trouble removing a region.  The cause of that seems to be AsyncWorldEdit, because after removeing AW everyhing went back to normal.

Just wanna let you know, since other people could run into the same issue. AsyncWorldEdit and WorldEdit 7 do not work well together with AreaShop.

`[19:20:55 INFO]: [AreaShop] Region vgs244 unrented because of inactivity for player FlauschigeDNS
[19:20:55 WARN]: [AreaShop] Task #53 for AreaShop v2.5.0 generated an exception
java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_144]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_144]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:150) ~[spigot_server.jar:git-Spigot-f6a273b-e3d7b2f]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:193) ~[spigot_server.jar:git-Spigot-f6a273b-e3d7b2f]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[spigot_server.jar:git-Spigot-f6a273b-e3d7b2f]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot_server.jar:git-Spigot-f6a273b-e3d7b2f]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_144]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_144]
	at me.wiefferink.areashop.handlers.WorldEditHandler7.restoreRegionBlocks(WorldEditHandler7.java:66) ~[?:?]
	at me.wiefferink.areashop.regions.GeneralRegion.restoreRegionBlocks(GeneralRegion.java:771) ~[?:?]
	at me.wiefferink.areashop.regions.GeneralRegion.handleSchematicEvent(GeneralRegion.java:1409) ~[?:?]
	at me.wiefferink.areashop.regions.BuyRegion.sell(BuyRegion.java:534) ~[?:?]
	at me.wiefferink.areashop.regions.BuyRegion.checkInactive(BuyRegion.java:565) ~[?:?]
	at me.wiefferink.areashop.shaded.bukkitdo.Do$9.run(Do.java:227) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot_server.jar:git-Spigot-f6a273b-e3d7b2f]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot_server.jar:git-Spigot-f6a273b-e3d7b2f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot_server.jar:git-Spigot-f6a273b-e3d7b2f]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot_server.jar:git-Spigot-f6a273b-e3d7b2f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot_server.jar:git-Spigot-f6a273b-e3d7b2f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot_server.jar:git-Spigot-f6a273b-e3d7b2f]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]`

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.):  Spigot 1.13.1
* Server version: version git-Spigot-f6a273b-e3d7b2f (MC: 1.13.1)
* AreaShop version: 2.5.0
* WorldEdit version: 7.0.0-beta-01;8975469
* WorldGuard version: 7.0.0-beta01;01dfebe
* Vault version: 1.7.1-b91
* AsyncWorldEdit: 3.5.4

**Comment by NLthijs48** [comment]
It looks like AsyncWorldEdit 3.5.4 is not compatible with WorldEdit 7, there is a new version available for Spigot 1.13 and WorldEdit 7 on the premium page though: https://www.spigotmc.org/resources/asyncworldedit-premium.9661/updates

So that version should be worth testing, I did not buy the plugin so I cannot test it myself yet.

**Comment by Sprungente** [comment]
I feel so free to link @SBPrime here because he is author of asyncworldedit. Maybe it is a help

**Comment by NLthijs48** [comment]
You could try the latest development build, it might work correctly now!
