### ISSUE TITLE
java.lang.NoSuchMethodError: com.sk89q.worldedit.EditSession.flushQueue()V

### ISSUE THREAD

**Issue by x1p** [NLthijs48/AreaShop#445]
**Current behavior**
```
> [00:43:16 WARN]: [AreaShop] Task #811 for AreaShop v2.5.0#259 generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldedit.EditSession.flushQueue()V
at me.wiefferink.areashop.handlers.WorldEditHandler7.restoreRegionBlocks(WorldEditHandler7.java:152) ~[?:?]
at me.wiefferink.areashop.regions.GeneralRegion.restoreRegionBlocks(GeneralRegion.java:771) ~[?:?]
at me.wiefferink.areashop.regions.GeneralRegion.handleSchematicEvent(GeneralRegion.java:1409) ~[?:?]
at me.wiefferink.areashop.regions.RentRegion.unRent(RentRegion.java:711) ~[?:?]
at me.wiefferink.areashop.regions.RentRegion.checkExpiration(RentRegion.java:358) ~[?:?]
at me.wiefferink.areashop.shaded.bukkitdo.Do$9.run(Do.java:227) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.1.jar:git-Paper-385]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.1.jar:git-Paper-385]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.1.jar:git-Paper-385]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.1.jar:git-Paper-385]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-385]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-385]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Steps to reproduce**
area rent period is over
This error spams thousends, millions of lines

**Your environment**
git-Paper-385 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
* AreaShop version: 2.5.0 till build 259
* WorldEdit version: WorldEdit v7.0.0-SNAPSHOT;3917-93a6964 or lower
* WorldGuard version: WorldGuard v7.0.0-SNAPSHOT;1753-0dc5781
* Vault version: 1.7.1

**Your config files**
default

**Comment by NLthijs48** [comment]
For now you can install the official WorldEdit 7 release to fix this: https://dev.bukkit.org/projects/worldedit/files/2618989

The newer development builds of WorldEdit break my integration. I'll work on a solution soon.

I'm merging this issue with #447, which is about the same problem
