### ISSUE TITLE
java.lang.NoSuchMethodError: com.sk89q.worldedit.EditSession.flushQueue()V

### ISSUE THREAD

**Issue by x1p** [NLthijs48/AreaShop#451]
**Current behavior**
```
> [10:59:57 WARN]: [AreaShop] Task #315724 for AreaShop v2.5.0#263 generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldedit.EditSession.flushQueue()V
at me.wiefferink.areashop.handlers.WorldEditHandler7.restoreRegionBlocks(WorldEditHandler7.java:150) ~[?:?]
at me.wiefferink.areashop.regions.GeneralRegion.restoreRegionBlocks(GeneralRegion.java:771) ~[?:?]
at me.wiefferink.areashop.regions.GeneralRegion.handleSchematicEvent(GeneralRegion.java:1409) ~[?:?]
at me.wiefferink.areashop.regions.RentRegion.unRent(RentRegion.java:711) ~[?:?]
at me.wiefferink.areashop.regions.RentRegion.checkExpiration(RentRegion.java:358) ~[?:?]
at me.wiefferink.areashop.shaded.bukkitdo.Do$9.run(Do.java:227) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-420]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.2.jar:git-Paper-420]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-420]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-420]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-420]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-420]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Expected behavior**
none

**Steps to reproduce**

see issue #447 

**Your environment**

* Server platform (Bukkit, Spigot, etc.): 
* Server version: git-Paper-419 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
* AreaShop version: build 265
* WorldEdit version: WorldEdit v7.0.0-SNAPSHOT;3926-d7c5282
* WorldGuard version: WorldGuard v7.0.0-SNAPSHOT;1753-0dc5781
* Vault version: Vault v1.7.1-b91*

**Your config files**
Not important

**Comment by NLthijs48** [comment]
Update to the [latest development build](http://wiefferink.me:8080/job/AreaShop/) to fix your issue, your stacktrace tells me you are running build 263, and build 265 and higher contain a fix for this issue.
