### ISSUE TITLE
Latest WE/WG vector system

### ISSUE THREAD

**Issue by x1p** [NLthijs48/AreaShop#452]
**Current behavior**
```
> [21:01:36 ERROR]: Error occurred while enabling AreaShop v2.5.0#263 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_181]
at me.wiefferink.areashop.AreaShop.onEnable(AreaShop.java:251) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-426]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.2.jar:git-Paper-426]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-426]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:438) ~[patched_1.13.2.jar:git-Paper-426]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:352) ~[patched_1.13.2.jar:git-Paper-426]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.2.jar:git-Paper-426]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.2.jar:git-Paper-426]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.2.jar:git-Paper-426]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-426]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-426]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.13.2.jar:git-Paper-426]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.13.2.jar:git-Paper-426]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
... 14 more
```

**Expected behavior**
no errors

**Steps to reproduce**

1. Download latest WE build
2. Download latest WG build
3. Start server
4. Error

**Your environment**
* Server platform (Bukkit, Spigot, etc.): Paper
* Server version: git-Paper-426 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
* AreaShop version: AreaShop v2.5.0#263
* WorldEdit version: WorldEdit v7.0.0-SNAPSHOT;3933-4e4ed6c
* WorldGuard version: WorldGuard v7.0.0-SNAPSHOT;1754-9169653

**Your config files**
default

**Comment by Sprungente** [comment]
i wrote about this issue with This. 
He'll fix it at the next free moment

**Comment by mibby** [comment]
@NLthijs48 Any possibility on a dev build with the new vector implementation in worldedit?

**Comment by i9hdkill** [comment]
Yes it's the same. Worldedit has rewrote it's Vector system. The new Vector class has been renamed, that's why plugins relying on the old class, erroing like in your log

**Comment by RubenStryker** [comment]
Are there any advances?

**Comment by x1p** [comment]
Areashop is the lastest plugin to update on this vector thing. We can't continue any further with updating many plugins which depend on a recent version of WorldEdit.
This is getting a bit frustrating now. :-/

**Comment by RubenStryker** [comment]
I appreciate your work and I hope that a good situation will be reached soon.
This plugin is vital for my server.

**Comment by SmallSansSerif** [comment]
Anyone have a working dev build with this?

**Comment by Questercraft** [comment]
> Anyone have a working dev build with this?

nothing works with the latest WG

**Comment by x1p** [comment]
The situation is beginning to get worse by the day. Since many, many plugins depend on a recent WorldEdit. So this plugin blocks updates for about 6 plugins for me personally. This annoys my staff and players in many ways.

**Comment by NLthijs48** [comment]
I implemented a solution for the vector changes in WorldEdit, you can install the [latest development build](http://wiefferink.me:8080/job/AreaShop/) to test it.

Let me know if you find any issues.
