### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by videosambo** [NLthijs48/AreaShop#453]
Console is filled error

[AreaShop] Task #172 for AreaShop v2.5.0 generated an exception
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
        at me.wiefferink.areashop.features.signs.RegionSign.update(RegionSign.java:157) ~[?:?]
        at me.wiefferink.areashop.shaded.bukkitdo.Do$9.run(Do.java:227) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by NLthijs48** [comment]
This issue has been fixed in the [development builds](http://wiefferink.me:8080/job/AreaShop/).
