### ISSUE TITLE
Bug areshop last version world guard and edit

### ISSUE THREAD

**Issue by Sly941** [NLthijs48/AreaShop#456]
**Current behavior**

I put the last build of world edit and keep the world and your plugin show me this:

Error occurred while enabling AreaShop v2.5.0#265 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_181]
at me.wiefferink.areashop.AreaShop.onEnable(AreaShop.java:251) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[Paper-1.13.2-b455.jar:git-Paper-455]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[Paper-1.13.2-b455.jar:git-Paper-455]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[Paper-1.13.2-b455.jar:git-Paper-455]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[Paper-1.13.2-b455.jar:git-Paper-455]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[Paper-1.13.2-b455.jar:git-Paper-455]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[Paper-1.13.2-b455.jar:git-Paper-455]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[Paper-1.13.2-b455.jar:git-Paper-455]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[Paper-1.13.2-b455.jar:git-Paper-455]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[Paper-1.13.2-b455.jar:git-Paper-455]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[Paper-1.13.2-b455.jar:git-Paper-455]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_181]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[Paper-1.13.2-b455.jar:git-Paper-455]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[Paper-1.13.2-b455.jar:git-Paper-455]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
... 14 more

**Steps to reproduce**

1. When the server starts

**Your environment**

* Server platform (Bukkit, Spigot, etc.): 
* Server version: Paper - 448
* AreaShop version: Areashop 2.5.0#265 
* WorldEdit version: 7.0.0-SNAPSHOT;3948
* WorldGuard version: 7.0.0-SNAPSHOT;1758
* Vault version: 1.5.6-b59

**Comment by WestIsMe** [comment]
The same issue on mine ^^ Running 1.3 spigot with Worldguard/-edit 7.0 and Areashop 2.5.0#265

Seems to be the exact same issue as they are having ^^

**Comment by Marek2k17** [comment]
same here, i wounder why they added this note to release 2.5.0, hasn't it been testet?

https://github.com/NLthijs48/AreaShop/releases/tag/v2.5.0
