### ISSUE TITLE
AreaShop not working with an update [Worldedit/Worldguard/Spigot?]

### ISSUE THREAD

**Issue by FuneralSuits** [NLthijs48/AreaShop#461]
### I'm assuming the issue with with PaperSpigot or Worldguard.

WorldGuard 7.0.0 Beta 2 was used and can be found [Here](https://dev.bukkit.org/projects/worldguard/files)

WorldEdit 7.0.0 Beta 4 was used and can be found [Here](https://dev.bukkit.org/projects/worldedit/files)

PaperSpigot 1.13.2 Build #480 was used and can be found [Here](https://papermc.io/downloads)

### This is the console output of what happens when trying to use any AreaShop commands:
[01:33:06] [Server thread/INFO]: FuneralSuits issued server command: /as
[01:33:06] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'as' in plugin AreaShop v2.5.0 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[patched_1.13.2.jar:git-Paper-476]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-476]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-476]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1792) ~[patched_1.13.2.jar:git-Paper-476]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1595) ~[patched_1.13.2.jar:git-Paper-476]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-476]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-476]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-476]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-476]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-476]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-476]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-476]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-476]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by NLthijs48** [comment]
I have just added support for the latest WorldEdit and WorldGuard, install the latest development build for a fix (see https://github.com/NLthijs48/AreaShop/issues/452).

Your error does not really point to the same issue, but please let me know if this solves it.
