### ISSUE TITLE
AreaShop does not start properly

### ISSUE THREAD

**Issue by 123hotdog1100** [NLthijs48/AreaShop#462]
**Current behavior**
[AreaShop] Enabling AreaShop v2.5.0
[11:19:50 ERROR]: Error occurred while enabling AreaShop v2.5.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_131]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_131]
        at me.wiefferink.areashop.AreaShop.onEnable(AreaShop.java:251) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        ... 14 more

**Expected behavior**
The plugin to load properly

**Steps to reproduce**

1. install areashop
2. does not start properly
3. 
4. 

**Your environment**

* Server platform (Bukkit, Spigot, etc.): 
* Server version: 
* AreaShop version: 2.50
* WorldEdit version: 7.0.0 beta-04
* WorldGuard version:  7.0.0-beta2
* Vault version: 1.7.1

**Your config files**
doesn't have one because it can't start

**Comment by NLthijs48** [comment]
Issue has been fixed, see https://github.com/NLthijs48/AreaShop/issues/452, install the latest development build to let it work.
