### ISSUE TITLE
Error occurred while enabling AreaShop v2.5.0#265 (Is it up to date?)

### ISSUE THREAD

**Issue by Ironic8b498** [NLthijs48/AreaShop#464]
**Current behavior**

**Expected behavior**

**Steps to reproduce**

1.  Startup server, get error near end of log
2.  Rent signs don't work
3.  
4. 

**Your environment**

* Server platform (Bukkit, Spigot, etc.): 
* Server version: Spigot/Bukkit 1.13.2
* AreaShop version: AreaShop-2.5.0-build-265
* WorldEdit version: worldedit-bukkit-7.0.0-SNAPSHOT-dist-#3962
* WorldGuard version: worldguard-legacy-7.0.0-SNAPSHOT-dist-#1763
* Vault version: Vault-1.7.1

**Your config files**

**Comment by SamBehner** [comment]
Also happening to me, I get an error after it as well
```
[20:39:40 ERROR]: Error occurred while enabling AreaShop v2.5.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_191]
        at me.wiefferink.areashop.AreaShop.onEnable(AreaShop.java:251) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot.jar:git-Spigot-a1f2566-a4c555b]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-a1f2566-a4c555b]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot.jar:git-Spigot-a1f2566-a4c555b]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot.jar:git-Spigot-a1f2566-a4c555b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot.jar:git-Spigot-a1f2566-a4c555b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot.jar:git-Spigot-a1f2566-a4c555b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot.jar:git-Spigot-a1f2566-a4c555b]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot.jar:git-Spigot-a1f2566-a4c555b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot.jar:git-Spigot-a1f2566-a4c555b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
        ... 14 more
```

**Comment by Fabrimat** [comment]
The problem happens also with WorldEdit 7.0.0 Beta 4 on Spigot 1.13.1

**Comment by SamBehner** [comment]
It seems to happen on any 1.13.2 beta

**Comment by SamBehner** [comment]
I used FAWE (I think thats what it's called, the AsyncWorldEdit thing) and it worked fine, the only thing is im on 1.13.2 and it has a few bugs (can't copy large spaces) because its not updated but other than that it fixed the issue

**Comment by NLthijs48** [comment]
AreaShop now supports the latest WorldEdit versions, see https://github.com/NLthijs48/AreaShop/issues/452, update to the latest development build.

I'm working on FAWE support, I'm tracking that [here](https://github.com/NLthijs48/AreaShop/issues/436).
