### ISSUE TITLE
IllegalPluginAccessException: Unable to find handler list for event me.wiefferink.areashop.events.RegionEvent

### ISSUE THREAD

**Issue by mibby** [NLthijs48/AreaShop#476]
AreaShops dev 282

@NLthijs48 Broke due to the removal here.
https://github.com/NLthijs48/AreaShop/commit/e0bad7397c18e460f3d298b76d3a128254ce54ce#diff-433c41e26436b019c24194bfd6cd2ca6R16

```
[22:01:35] [Server thread/INFO]: [AreaShop] Enabling AreaShop v2.6.0#282
[22:01:35] [Log4j2-TF-1-AsyncLogger[AsyncContext@799f7e29]-1/INFO]: [DiscordSRV] [JDA] Finished Loading!
[22:01:35] [Server thread/ERROR]: Error occurred while enabling AreaShop v2.6.0#282 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event me.wiefferink.areashop.events.RegionEvent. Static getHandlerList method required!
	at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:604) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:602) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:602) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:545) ~[patched_1.13.2.jar:git-Paper-509]
	at me.wiefferink.areashop.features.RegionFeature.listen(RegionFeature.java:35) ~[?:?]
	at me.wiefferink.areashop.managers.FeatureManager.<init>(FeatureManager.java:44) ~[?:?]
	at me.wiefferink.areashop.AreaShop.onEnable(AreaShop.java:346) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-509]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[22:01:35] [Server thread/INFO]: [AreaShop] Disabling AreaShop v2.6.0#282
```

```
[22:01:38] [Server thread/INFO]: [ShopChest] Enabling ShopChest v1.13-SNAPSHOT
[22:01:38] [Server thread/ERROR]: Error occurred while enabling ShopChest v1.13-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: me/wiefferink/areashop/AreaShop
	at de.epiceric.shopchest.ShopChest.loadExternalPlugins(ShopChest.java:269) ~[?:?]
	at de.epiceric.shopchest.ShopChest.onEnable(ShopChest.java:172) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-509]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: me.wiefferink.areashop.AreaShop
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:138) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84) ~[patched_1.13.2.jar:git-Paper-509]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 13 more
[22:01:38] [Server thread/INFO]: [ShopChest] Disabling ShopChest v1.13-SNAPSHOT
[22:01:38] [Server thread/ERROR]: Error occurred while disabling ShopChest v1.13-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
	at de.epiceric.shopchest.ShopChest.onDisable(ShopChest.java:214) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:330) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-509]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by mibby** [comment]
Seemingly fixed in commit https://github.com/NLthijs48/AreaShop/commit/1035b6b41bed1601949aaf020d097e77f6cd9942. Thanks!

**Comment by NLthijs48** [comment]
Ah I broke this indeed, has been fixed in a later commit. Still thanks for the heads-up :)
