### ISSUE TITLE
Incompatibility with FAWE 1.13 branch.

### ISSUE THREAD

**Issue by mibby** [NLthijs48/AreaShop#480]
AreaShops dev 284
FastAsyncWorldEdit 1.13 compiled as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/24fbc86cdd79b8ce13359342bc422ce1fb25a0d2

AreaShops is detecting FAWE and using the old Vector logic. New FAWE should be upstream compatible with WorldEdit and WorldGuard.

```
[20:03:11] [Server thread/INFO]: [AreaShop] Enabling AreaShop v2.6.0#284
[20:03:11] [Server thread/ERROR]: Error occurred while enabling AreaShop v2.6.0#284 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_202]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_202]
	at me.wiefferink.areashop.AreaShop.onEnable(AreaShop.java:297) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-525]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_202]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:138) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84) ~[patched_1.13.2.jar:git-Paper-525]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_202]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202]
	... 14 more

```

**Comment by NLthijs48** [comment]
Thanks for reporting this, I'll try updating the FAWE integration soon. Hopefully I can remove the integration entirely and just use the WorldEdit one

**Comment by mibby** [comment]
Let me know if you need any help testing!

**Comment by mibby** [comment]
RE: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/56#issuecomment-476442498

Removing all old worldedit/worldguard modules and the actual FAWE integration hook, compatibility seems to be fine with FAWE 1.13 and FAWE breaking branch. As far as I know, it should be upstream compatible with vanilla worldedit now and works fine from my testing.

**Comment by Fabrimat** [comment]
> RE: [IntellectualSites/FastAsyncWorldEdit-1.13#56 (comment)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/56#issuecomment-476442498)
> 
> Removing all old worldedit/worldguard modules and the actual FAWE integration hook, compatibility seems to be fine with FAWE 1.13 and FAWE breaking branch. As far as I know, it should be upstream compatible with vanilla worldedit now and works fine from my testing.

Can you please share your edits?

**Comment by imDaniX** [comment]
Sill relevant. Using Paper-624, WorldGuard beta 3, latest FAWE from empcraft.com/fawe/download/ and latest AreaShop build.

**Comment by imDaniX** [comment]
Still relevant. WorldGuard 7.0.0-beta-03, FAWE-1.13-129, AreaShio build 287

**Comment by Raphy123** [comment]
And for 1.14.4 ?

**Comment by Fabrimat** [comment]
> And for 1.14.4 ?

If you need updates, Areashop is unreliable. Switch to something like Residence.
