### ISSUE TITLE
NullPointerException - fawe.object.clipboard.DiskOptimizedClipboard.setBlock

### ISSUE THREAD

**Issue by mibby** [NLthijs48/AreaShop#482]
FAWE 1.13 compiled as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/24fbc86cdd79b8ce13359342bc422ce1fb25a0d2
AreaShop compiled as of commit https://github.com/NLthijs48/AreaShop/commit/d7cdff0b2285bc335489654a5ba54bd8ba09ee77

Custom compiled AreaShops in an attempt to get it working with FAWE 1.13 branch. Removed all dependency modules except for fastasyncworldedit, worldedit-7_beta_4, & worldguard-7_beta_2. As well as cloned the WorldEdit and WorldGuard handler files for v7 into fastasyncworldedit (while keeping the FAWE handler names).

FAWE's new 1.13 branch _should_ be upstream compatible with WorldEdit 7 to avoid any plugin dependency issues. However running into this issue when unrenting. :(

```
[21:11:53] [Server thread/INFO]: player issued server command: /as unrent
[21:11:53] [Server thread/WARN]: java.lang.NullPointerException
[21:11:53] [Server thread/WARN]: 	at com.boydti.fawe.object.clipboard.DiskOptimizedClipboard.setBlock(DiskOptimizedClipboard.java:528)
[21:11:53] [Server thread/WARN]: 	at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.readVersion1(SpongeSchematicReader.java:438)
[21:11:53] [Server thread/WARN]: 	at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.read(SpongeSchematicReader.java:109)
[21:11:53] [Server thread/WARN]: 	at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.read(SpongeSchematicReader.java:104)
[21:11:53] [Server thread/WARN]: 	at me.wiefferink.areashop.handlers.FastAsyncWorldEditHandler.restoreRegionBlocks(FastAsyncWorldEditHandler.java:102)
[21:11:53] [Server thread/WARN]: 	at me.wiefferink.areashop.regions.GeneralRegion.restoreRegionBlocks(GeneralRegion.java:794)
[21:11:53] [Server thread/WARN]: 	at me.wiefferink.areashop.regions.GeneralRegion.handleSchematicEvent(GeneralRegion.java:1432)
[21:11:53] [Server thread/WARN]: 	at me.wiefferink.areashop.regions.RentRegion.unRent(RentRegion.java:694)
[21:11:53] [Server thread/WARN]: 	at me.wiefferink.areashop.commands.UnrentCommand.execute(UnrentCommand.java:79)
[21:11:53] [Server thread/WARN]: 	at me.wiefferink.areashop.managers.CommandManager.onCommand(CommandManager.java:144)
[21:11:53] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[21:11:53] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[21:11:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734)
[21:11:53] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1797)
[21:11:53] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1605)
[21:11:53] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[21:11:53] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[21:11:53] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[21:11:53] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:11:53] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:11:53] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[21:11:53] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011)
[21:11:53] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[21:11:53] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[21:11:53] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[21:11:53] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by NLthijs48** [comment]
I assume this is because of #480? I'll make sure to test this as well while working on that one.

**Comment by mibby** [comment]
Possibly, but I believe the SpongeSchematicReader may just be unfinished in the new 1.13 branch since half of it is commented out.

https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/blob/new-vector-system/worldedit-core/src/main/java/com/sk89q/worldedit/extent/clipboard/io/SpongeSchematicReader.java

https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/56#issuecomment-468403390

**Comment by mibby** [comment]
@NLthijs48 RE: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/56#issuecomment-476442498

AreaShops with a removed FAWE module / detection (using just the latest WorldEdit beta module) seems to work fine with the new FAWE 1.13 branch as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/85bfd16d7c16613e79f49d3acaa17007c09baa3e.
