### ISSUE TITLE
Hook into FAWE

### ISSUE THREAD

**Issue by Ironic8b498** [NLthijs48/AreaShop#496]
Besides updating to 1.14, if it's not to much could you add FAWE support along with WE

**Comment by elise1886** [comment]
I agree and need this desperately

**Comment by OnrechtmatigeDaad** [comment]
Exactly. Back in januari support was added for FAWE, but in the dev builds support was already broken in [this commit from December](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/d4157b7e0e6421c1fc8525834695d88eed9f7ea1#diff-ae792d930135c47308b31e51caf44976) which deleted the Vector.java file, which is the cause for the following error when starting the plugin:

`[21:12:11] [Server thread/ERROR]: Error occurred while enabling AreaShop v2.6.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_212]
	at me.wiefferink.areashop.AreaShop.onEnable(AreaShop.java:296) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[server.jar:git-Spigot-1a3504a-84f3da3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [server.jar:git-Spigot-1a3504a-84f3da3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [server.jar:git-Spigot-1a3504a-84f3da3]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [server.jar:git-Spigot-1a3504a-84f3da3]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [server.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [server.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [server.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [server.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [server.jar:git-Spigot-1a3504a-84f3da3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [server.jar:git-Spigot-1a3504a-84f3da3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:136) ~[server.jar:git-Spigot-1a3504a-84f3da3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82) ~[server.jar:git-Spigot-1a3504a-84f3da3]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	... 14 more`

I hope this information helps in fixing it. I'd try to fix it myself if I could, but my experience with WE is like, non-existent.
