### ISSUE TITLE
org.bukkit.material.MaterialData cannot be cast to org.bukkit.material.Sign

### ISSUE THREAD

**Issue by rmb938** [NLthijs48/AreaShop#502]
**Current behavior**

All ways creating shop signs fail

**Expected behavior**

Shop signs to be created

**Steps to reproduce**

1. Spigot 1.14.1
2. Create a region
3. Try to add a sign for the region

**Your environment**

* Server platform (Bukkit, Spigot, etc.):  Spigot
* Server version: git-Spigot-8043ebc-9bda413 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)
* AreaShop version: 2.6.0
* WorldEdit version: 7.0.0-SNAPSHOT;4244-bc8e477
* WorldGuard version:  7.0.0-SNAPSHOT;1865-b27f187
* Vault version: 1.7.2-b107

```
[18:23:58] [Server thread/ERROR]: Could not pass event SignChangeEvent to AreaShop v2.6.0#285
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-8043ebc-9bda413]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-8043ebc-9bda413]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot.jar:git-Spigot-8043ebc-9bda413]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2406) ~[spigot.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:44) ~[spigot.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:10) ~[spigot.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872) [spigot.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot.jar:git-Spigot-8043ebc-9bda413]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.ClassCastException: org.bukkit.material.MaterialData cannot be cast to org.bukkit.material.Sign
	at me.wiefferink.areashop.features.signs.SignsFeature.onSignChange(SignsFeature.java:281) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-8043ebc-9bda413]
	... 17 more

```

**Comment by rmb938** [comment]
Actually it seems to only happen with wall signs

**Comment by NobleStrike** [comment]
Yeah same issue, it seems to be the only obvious thing broken on 1.14.1 for this plugin so far. Hopefully it gets patched sometime soon.

**Comment by AustinGarrettRichards** [comment]
Same issue. Still happening on build 292

**Comment by AustinGarrettRichards** [comment]
Fixed on build 292 :D!

**Comment by NLthijs48** [comment]
You can try the development build that is suitable for 1.14, you can download it here: http://jenkins.wiefferink.me/job/AreaShop/.

I'll release this as an official version soon.
