### ISSUE TITLE
Area shop does not unrent 

### ISSUE THREAD

**Issue by gmanc2** [NLthijs48/AreaShop#534]
**Current behavior**

Shop does not unrent after time has expired

**Desired behavior**

To unrent

**Your environment**

* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.14.4
* AreaShop version: 2.6.0
* WorldEdit version: 7.0.1
* WorldGuard version: 7.0.1
* Vault version: 1.7.3

[backup.zip](https://github.com/NLthijs48/AreaShop/files/3678988/backup.zip)

**Your config files**

**Comment by gmanc2** [comment]
[AreaShop]: Do.forAll() iteration failed for object: ps1 (me.wiefferink.areashop.regions.RentRegion)
Console 22:43:20
java.lang.RuntimeException: The operation to load user data for '1ab32698-d152-4bcb-8e87-e215c1f29de3' was cancelled by LuckPerms. This is NOT a bug.
The lookup request was made on the main server thread. It is not safe to execute a request to
load data for offline players from the database in this context.
If you are a plugin author, please consider making your request asynchronously.
Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true
in the LP config, but should consider the consequences (lag) before doing so.
at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.lookupUser(LuckPermsVaultPermission.java:163) ~[?:?]
at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.userHasPermission(LuckPermsVaultPermission.java:189) ~[?:?]
at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.playerHas(AbstractVaultPermission.java:154) ~[?:?]
at me.wiefferink.areashop.AreaShop.hasPermission(AreaShop.java:651) ~[?:?]
at me.wiefferink.areashop.regions.RentRegion.rent(RentRegion.java:437) ~[?:?]
at me.wiefferink.areashop.regions.RentRegion.extend(RentRegion.java:422) ~[?:?]
at me.wiefferink.areashop.regions.RentRegion.checkExpiration(RentRegion.java:350) ~[?:?]
at me.wiefferink.areashop.shaded.bukkitdo.Do$9.run(Do.java:230) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-187]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-187]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148) ~[patched_1.14.4.jar:git-Paper-187]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-187]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-187]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-187]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

This also appeared.
