### ISSUE TITLE
Areashop and  WorldEdit 7.2.0 Beta 

### ISSUE THREAD

**Issue by cbronak** [NLthijs48/AreaShop#563]
**Current behavior**
Maybe a lil bit early, but WorldEdit 7.2.0 Beta for 1.16.1 was released yesterday and Areashop doesnt like it. 

**Your environment**
* Server platform (Bukkit, Spigot, etc.): 
* Server version:  Paper-354 (1.15.2)
* AreaShop version: v2.6.0#299
* WorldEdit version: 7.2.0 Beta
* WorldGuard version:  7.0.2-SNAPSHOT;bf2593e
* Vault version: v1.7.2-b107

[15:44:38] [Server thread/INFO]: [AreaShop] Enabling AreaShop v2.6.0#299
[15:44:38] [Server thread/ERROR]: Error occurred while enabling AreaShop v2.6.0#299 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_221]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_221]
        at me.wiefferink.areashop.AreaShop.onEnable(AreaShop.java:299) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-371]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-371]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-371]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-371]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-371]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-371]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-371]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-371]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-371]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-371]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_221]
        ... 12 more
[15:44:38] [Server thread/INFO]: [AreaShop] Disabling AreaShop v2.6.0#299

**Comment by imim332** [comment]
You're not supposed to be using a 1.16 worldedit on a 1.15.2 server, worldedit often breaks with every version.

**Comment by x1p** [comment]
According to the website, this WE version is suitable for 1.13.2 - 1.16.1
