### ISSUE TITLE
AreaShop doesn't start on MC 1.16.1

### ISSUE THREAD

**Issue by francoispope** [NLthijs48/AreaShop#564]
**Current behavior**

Error while enabling AreaShop v2.6.0#299
~~~
[22:50:24] [Server thread/INFO]: [AreaShop] Enabling AreaShop v2.6.0#299
[22:50:24] [Server thread/ERROR]: Error occurred while enabling AreaShop v2.6.0#299 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_212]
	at me.wiefferink.areashop.AreaShop.onEnable(AreaShop.java:299) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot_server-1.16.1.jar:git-Spigot-758abbe-614fbae]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot_server-1.16.1.jar:git-Spigot-758abbe-614fbae]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot_server-1.16.1.jar:git-Spigot-758abbe-614fbae]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:489) ~[spigot_server-1.16.1.jar:git-Spigot-758abbe-614fbae]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:403) ~[spigot_server-1.16.1.jar:git-Spigot-758abbe-614fbae]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:439) ~[spigot_server-1.16.1.jar:git-Spigot-758abbe-614fbae]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219) ~[spigot_server-1.16.1.jar:git-Spigot-758abbe-614fbae]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:811) ~[spigot_server-1.16.1.jar:git-Spigot-758abbe-614fbae]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:165) ~[spigot_server-1.16.1.jar:git-Spigot-758abbe-614fbae]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot_server-1.16.1.jar:git-Spigot-758abbe-614fbae]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot_server-1.16.1.jar:git-Spigot-758abbe-614fbae]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	... 13 more
~~~

**Expected behavior**

* Start plugin
* Create a default config.yml

**Steps to reproduce**

1. Place plugins (Vault, WorldGuard, WorldEdit, AreaShop) in `/plugins/`
2. Start spigot server

**Your environment**

* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.16.1
* AreaShop version: 2.6.0#299
* WorldEdit version: v7.2.0-beta-01+0eb9ac7
* WorldGuard version: v7.0.4-beta1;bc551da
* Vault version: v1.7.2-b107

**Your config files**

* WorldGuard: [config.yml.zip](https://github.com/NLthijs48/AreaShop/files/4839518/config.yml.zip)
* AreaShop: doesn't create one 😢

**Comment by Syrkulous** [comment]
Areashop has a config.

The issue is that AreaShop is no longer updated as you can see the last update was 10-13 months ago.

The newly updated WorldEdit isn't compatible with AreaShop which is why it wont load.
You will need to find something to replace AreaShop sadly. And if you do, please respond here or to my Discord Kry'S#8317

**Comment by francoispope** [comment]
> Areashop has a config.

I know it has a config, but for testing purposes I had removed it to regenerate a fresh default config. The result was that it doesn’t generate one due to the error.

**Comment by MrKiller01** [comment]
It is so sad to see that a lot of plugin makers turn their heads and don't care anymore, knowing that a lot of people are enthusiastic about them, worst is, those plugins they feel to make their income go up, make them premium, and then let it bleed dry, KNOWING that there still are people who buy such a plugin and the owner does not care.....
I do not understand why people commit themselves to a project and then simply drop it like it is nothing.
So sad....  They should have a sort of contract with the website they post their work on to finish the work they make and make sure someone takes over if shit happens, but there is no eula, no contract, no regulation, it is a wild zoo out there...

**Comment by fierceeo** [comment]
This is an issue with areashop using an outdated api (world edit v6) it needs to be updated to v7

**Comment by fierceeo** [comment]
I created a fork, and updated the latest worldedit module, but for some reason I still get that error. I’m reasonably new to using maven modules so it could be that.

**Comment by imim332** [comment]
What's the new error you're getting

**Comment by FatherWh0** [comment]
I would also like to request that, if a working fork is created or an alternative found,, it be posted here. We very much depend upon this plugin on my server.
For now, I'm using the older worldedit as it doesn't break with 1.16.1. If anyone has a better solution please post here.

**Comment by Realeehop** [comment]
Curtis Made A Great Fork: https://github.com/Curtis73/AreaShop/releases
Help That Helps.

**Comment by kamil445** [comment]
> 
> 
> Curtis Made A Great Fork: https://github.com/Curtis73/AreaShop/releases
> Help That Helps.

Thanks!
