### ISSUE TITLE
Addsign error

### ISSUE THREAD

**Issue by Monaldcry7788** [NLthijs48/AreaShop#575]
Console error:
[09:47:53 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'areashop' in plugin AreaShop v2.6.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-294]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-294]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2008) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1819) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1772) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-294]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: java.lang.NullPointerException
        at org.bukkit.material.Sign.getFacing(Sign.java:134) ~[patched_1.16.4.jar:git-Paper-294]
        at me.wiefferink.areashop.commands.AddsignCommand.execute(AddsignCommand.java:96) ~[?:?]
        at me.wiefferink.areashop.managers.CommandManager.onCommand(CommandManager.java:142) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-294]

1.  Add a sign

* Server platform: Paper
* Server version: Paper 1.16.4
* AreaShop version: 2.6.0
* WorldEdit version: 7.2.0
* WorldGuard version: 7.0.4-beta1
* Vault version: 1.7.3-b131

[Config.zip](https://github.com/NLthijs48/AreaShop/files/5646809/Config.zip)

**Comment by Curtis73** [comment]
Hey, I've made a fork which should fix this issue - you can get it here: https://github.com/Curtis73/AreaShop/releases/tag/v2.6.2
