### ISSUE TITLE
1.16.5 regions not rentable/buyable setting up sign

### ISSUE THREAD

**Issue by saintblair11** [NLthijs48/AreaShop#582]
**Current behavior**

[16:05:13 INFO]: [WorldGuard] Region data changes made in 'runescape_poh' have been background saved
[16:05:16 ERROR]: Could not pass event BlockPhysicsEvent to AreaShop v2.6.0
java.lang.ClassCastException: null
[16:05:36 INFO]: test3 placed a sign @ adventure_craft_tutorial: x-240, z78;[asrent];tut_pub_room_2;1 d;5
[16:05:36 ERROR]: Could not pass event SignChangeEvent to AreaShop v2.6.0
java.lang.ClassCastException: class org.bukkit.material.MaterialData cannot be cast to class org.bukkit.material.Sign (org.bukkit.material.MaterialData and org.bukkit.material.Sign are in unnamed module of loader 'app')
at me.wiefferink.areashop.features.signs.SignsFeature.onSignChange(SignsFeature.java:280) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor503.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-1.16.5.jar:git-Paper-562]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-1.16.5.jar:git-Paper-562]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-1.16.5.jar:git-Paper-562]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[paper-1.16.5.jar:git-Paper-562]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2956) ~[paper-1.16.5.jar:git-Paper-562]
at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$18(PlayerConnection.java:2913) ~[paper-1.16.5.jar:git-Paper-562]
at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$1(PlayerConnection.java:473) ~[paper-1.16.5.jar:git-Paper-562]
at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$3(PlayerConnection.java:487) ~[paper-1.16.5.jar:git-Paper-562]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[paper-1.16.5.jar:git-Paper-562]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[paper-1.16.5.jar:git-Paper-562]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[paper-1.16.5.jar:git-Paper-562]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[paper-1.16.5.jar:git-Paper-562]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[paper-1.16.5.jar:git-Paper-562]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[paper-1.16.5.jar:git-Paper-562]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[paper-1.16.5.jar:git-Paper-562]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206) ~[paper-1.16.5.jar:git-Paper-562]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[paper-1.16.5.jar:git-Paper-562]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[paper-1.16.5.jar:git-Paper-562]
at java.lang.Thread.run(Thread.java:834) [?:?]
[16:06:13 INFO]: [WorldGuard] Region data changes made in 'runescape_poh' have been background saved

seperate console error im not shure what is triggering it: could not pass blockbreakevent to areashop 2.6.0

**Expected behavior**

region be rentable/buyable when someone interacts with the sign

**Steps to reproduce**

1. create region, wall 1 block thick for buffer area, sign placed on outside of room with:
2.  [asrent]
tut_pub_room_2
1 d
5

3. sign places as normal, may have colouring but wont make the region rentable/buyable when clicked on.

**Your environment**

* Server platform (Bukkit, Spigot, etc.): spigot paper
* Server version: This server is running Paper version git-Paper-562 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
* AreaShop version:  2.6.0
* WorldEdit version:  worldedit-bukkit-7.2.4
* WorldGuard version:  worldguard-bukkit-7.0.4
* Vault version:  1.7.3-b131
[areashop and worldguard configs.zip](https://github.com/NLthijs48/AreaShop/files/6410356/areashop.and.worldguard.configs.zip)

**Your config files**

**Comment by Curtis73** [comment]
Hey, my fork should fix this issue - you can get it here: https://github.com/Curtis73/AreaShop/releases/tag/v2.6.3
