### ISSUE TITLE
Could not pass event BlockPhysicsEvent to AreaShop v2.6.0

### ISSUE THREAD

**Issue by yuankun1** [NLthijs48/AreaShop#584]
[18:12:58] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to AreaShop v2.6.0
java.lang.ClassCastException: class org.bukkit.material.MaterialData cannot be cast to class org.bukkit.material.Sign (org.bukkit.material.MaterialData and org.bukkit.material.Sign are in unnamed module of loader 'app')
	at me.wiefferink.areashop.features.signs.SignsFeature.onIndirectSignBreak(SignsFeature.java:119) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1284.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-675]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-675]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-675]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.World.a(World.java:672) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.World.applyPhysics(World.java:627) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.TileEntityChest.onOpen(TileEntityChest.java:286) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.TileEntityChest.startOpen(TileEntityChest.java:255) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.InventoryLargeChest.startOpen(InventoryLargeChest.java:132) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.ContainerChest.<init>(ContainerChest.java:84) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.ContainerChest.b(ContainerChest.java:76) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.BlockChest$DoubleInventory.createMenu(BlockChest.java:114) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.EntityPlayer.openContainer(EntityPlayer.java:1419) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.BlockChest.interact(BlockChest.java:261) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.BlockBase$BlockData.interact(BlockBase.java:638) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:544) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1705) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:32) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:10) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1263) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1256) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1217) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1131) ~[patched_1.16.5.jar:git-Paper-675]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-675]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by ScottyRobinson** [comment]
We're getting the same issue. Any update for this?

**Comment by jaroslawjanas** [comment]
Getting this as well on `1.18.2`

**Comment by MagnumEis** [comment]
You can just use oak signs.
i had the same error and i used spruce signs.
it works for me now

**Comment by hellfire989** [comment]
@yuankun1 @ScottyRobinson @jaroslawjanas @MagnumEis

Did anyone ever find a fix for this issue? I'm still getting this issue in 1.20.1 when trying to place flat signs on certain blocks :(

19.09 04:14:59 [Server] [ERROR] Could not pass event BlockPhysicsEvent to AreaShop v2.6.0
19.09 04:14:59 [Server] [INFO] java.lang.NullPointerException: Cannot invoke "org.bukkit.block.BlockFace.getModX()" because "face" is null
19.09 04:14:59 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.getRelative(CraftBlock.java:265) ~[paper-1.20.1.jar:git-Paper-"517f8fb"]
19.09 04:14:59 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.getRelative(CraftBlock.java:260) ~[paper-1.20.1.jar:git-Paper-"517f8fb"]
19.09 04:14:59 [Server] [INFO] at me.wiefferink.areashop.features.signs.SignsFeature.onIndirectSignBreak(SignsFeature.java:120) ~[AreaShop.jar:?]
19.09 04:14:59 [Server] [INFO] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor238.execute(Unknown Source) ~[?:?]
19.09 04:14:59 [Server] [INFO] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
19.09 04:14:59 [Server] [INFO] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-"517f8fb"]
19.09 04:14:59 [Server] [INFO] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
19.09 04:14:59 [Server] [INFO] at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-"517f8fb"]
19.09 04:14:59 [Server] [INFO] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-"517f8fb"]
19.09 04:14:59 [Server] [INFO] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
19.09 04:14:59 [Server] [INFO] at net.minecraft.world.level.Level.notifyAndUpdatePhysics(Level.java:736) ~[?:?]
19.09 04:14:59 [Server] [INFO] at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:459) ~[paper-1.20.1.jar:git-Paper-"517f8fb"]
19.09 04:14:59 [Server] [INFO] at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:597) ~[?:?]
19.09 04:14:59 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2015) ~[?:?]
19.09 04:14:59 [Server] [INFO] at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
19.09 04:15:01 [Server] [INFO] at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
19.09 04:15:01 [Server] [INFO] at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
19.09 04:15:01 [Server] [INFO] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-"517f8fb"]
19.09 04:15:01 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
19.09 04:15:01 [Server] [INFO] at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
19.09 04:15:01 [Server] [INFO] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-"517f8fb"]
19.09 04:15:01 [Server] [INFO] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-"517f8fb"]
19.09 04:15:01 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
19.09 04:15:01 [Server] [INFO] at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-"517f8fb"]
19.09 04:15:01 [Server] [INFO] at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-"517f8fb"]
19.09 04:15:01 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
19.09 04:15:01 [Server] [INFO] at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-"517f8fb"]
19.09 04:15:01 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-"517f8fb"]
19.09 04:15:01 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-"517f8fb"]
19.09 04:15:01 [Server] [INFO] at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by hellfire989** [comment]
@NLthijs48 Sorry to bother, but I'm getting this error again in 2023 that I thought was fixed in #507.

Any way I can fix this?
