### ISSUE TITLE
BlockPhysicsEvent error

### ISSUE THREAD

**Issue by tika** [NLthijs48/AreaShop#589]
07.08 18:47:54 [Server] ERROR Could not pass event BlockPhysicsEvent to AreaShop v2.6.0
07.08 18:47:54 [Server] INFO java.lang.NullPointerException: Cannot invoke "org.bukkit.block.BlockFace.getModX()" because "face" is null
07.08 18:47:54 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.getRelative(CraftBlock.java:255) ~[patched_1.17.1.jar:git-Paper-"377a60d"]
07.08 18:47:54 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlock.getRelative(CraftBlock.java:250) ~[patched_1.17.1.jar:git-Paper-"377a60d"]
07.08 18:47:54 [Server] INFO at me.wiefferink.areashop.features.signs.SignsFeature.onIndirectSignBreak(SignsFeature.java:120) ~[?:?]
07.08 18:47:54 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor408.execute(Unknown Source) ~[?:?]
07.08 18:47:54 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-"377a60d"]
07.08 18:47:54 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-"377a60d"]
07.08 18:47:54 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-"377a60d"]
07.08 18:47:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-"377a60d"]
07.08 18:47:54 [Server] INFO at net.minecraft.world.level.Level.notifyAndUpdatePhysics(Level.java:575) ~[?:?]
07.08 18:47:54 [Server] INFO at net.minecraft.world.item.ItemStack.placeItem(ItemStack.java:413) ~[patched_1.17.1.jar:git-Paper-"377a60d"]
07.08 18:47:54 [Server] INFO at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:571) ~[?:?]
07.08 18:47:54 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1723) ~[?:?]
07.08 18:47:54 [Server] INFO at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
07.08 18:47:54 [Server] INFO at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:9) ~[?:?]
07.08 18:47:54 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
07.08 18:47:54 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-"377a60d"]
07.08 18:47:58 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
07.08 18:47:58 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
07.08 18:47:58 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-"377a60d"]
07.08 18:47:58 [Server] INFO at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-"377a60d"]
07.08 18:47:58 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
07.08 18:47:58 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-"377a60d"]
07.08 18:47:58 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-"377a60d"]
07.08 18:47:58 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
07.08 18:47:58 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1281) ~[patched_1.17.1.jar:git-Paper-"377a60d"]
07.08 18:47:58 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[patched_1.17.1.jar:git-Paper-"377a60d"]
07.08 18:47:58 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-"377a60d"]
07.08 18:47:58 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by tika** [comment]
Duplicate issue #584.
