### ISSUE TITLE
1.8.2 Sign Change Error

### ISSUE THREAD

**Issue by jaroslawjanas** [NLthijs48/AreaShop#598]
**Current behavior**
Placing a sign like this.
![image](https://user-images.githubusercontent.com/28691446/159134411-fcfe6e4f-3298-471c-b1e2-171eb512a05d.png)

Generates the following error.
```
[18:39:02 ERROR]: Could not pass event SignChangeEvent to AreaShop v2.6.0
java.lang.ClassCastException: class org.bukkit.material.MaterialData cannot be cast to class org.bukkit.material.Sign (org.bukkit.material.MaterialData and org.bukkit.material.Sign are in unnamed module of loader java.net.URLClassLoader @67424e82)
        at me.wiefferink.areashop.features.signs.SignsFeature.onSignChange(SignsFeature.java:280) ~[AreaShop.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor305.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-260]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.updateSignText(ServerGamePacketListenerImpl.java:3113) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleSignUpdate$19(ServerGamePacketListenerImpl.java:3060) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$filterTextPacket$1(ServerGamePacketListenerImpl.java:473) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-260]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-260]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-260]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-260]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-260]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-260]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-260]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-260]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
 

**Expected behavior**
It should not error.

**Steps to reproduce**
Place the sign

**Your environment**

* Server platform (Bukkit, Spigot, etc.): 
* Server version: `git-Paper-259 (MC: 1.18.2)`
* AreaShop version: `AreaShop 2.6.0`
* WorldEdit version: `worldedit-bukkit-7.2.11-SNAPSHOT-dist`
* WorldGuard version: `worldguard-bukkit-7.0.7-dist` 
* Vault version: `Vault 1.7.3`

**Your config files**

[configs.zip](https://github.com/NLthijs48/AreaShop/files/8309887/configs.zip)

**Comment by QueenOfTheSea21** [comment]
I too get this same error but on 1.18.2. Nothing I do works. I have the region set up using the commands but signs don't work; Not even when placed on the ground.

**Comment by jaroslawjanas** [comment]
@QueenOfTheSea21 
If you are not upgrading from an older version I suggest using [ARM](https://github.com/alex9849/advanced-region-market) until this issue is resolved.

Which might be never considering the last commit was in *2020*.

**Comment by QueenOfTheSea21** [comment]
unfortunately, i am upgrading from an older version
