### ISSUE TITLE
Console error on start-up

### ISSUE THREAD

**Issue by AsylumDreams** [NLthijs48/AreaShop#95]
Printing in console after update. Default file does exist and seems fine - it's the auto-generated file:

general:
  enableRestore: true
  schematicProfile: 'default'
  eventCommandProfile: 'default'
  signProfile: 'default'
  flagProfile: 'default'
  teleportLocationY: bottom
  teleportIntoRegion: true
  teleportToSignIntoRegion: true
  restrictedToWorld: true
  restrictedToRegion: true
rent:
  price: 1000
  duration: '5 day'
  moneyBack: 20
  maxExtends: 3
  maxRentTime: 40320
  inactiveTimeUntilUnrent: 21600
  warningOnLoginTime: '1 day'
  expirationWarningProfile: 'default'
buy:
  price: 10000
  moneyBack: 80
   inactiveTimeUntilSell: 21600

And the log file is here:

[03:06:14] [Server thread/INFO]: [AreaShop] Enabling AreaShop v2.2.1
[03:06:14] [Server thread/ERROR]: Cannot load configuration from stream
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 66, column 3:
      price: 10000
      ^
expected <block end>, but found BlockMappingStart
 in 'string', line 71, column 4:
       inactiveTimeUntilSell: 21600
       ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:240) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at nl.evolutioncoding.areashop.managers.FileManager.loadDefaultFile(FileManager.java:866) [AreaShop.jar:?]
	at nl.evolutioncoding.areashop.managers.FileManager.loadFiles(FileManager.java:813) [AreaShop.jar:?]
	at nl.evolutioncoding.areashop.AreaShop.onEnable(AreaShop.java:194) [AreaShop.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 66, column 3:
      price: 10000
      ^
expected <block end>, but found BlockMappingStart
 in 'string', line 71, column 4:
       inactiveTimeUntilSell: 21600
       ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
	... 16 more
[03:06:14] [Server thread/WARN]: [AreaShop] File 'default.yml' is empty, check for errors in the log.
[03:06:14] [Server thread/ERROR]: [AreaShop] The plugin has not started, fix the errors listed above

**Comment by NLthijs48** [comment]
Please post your default.yml in between two backticks (like `) or using pastebin.com, I need to be able to see the indentation to see what is wrong with the file.

**Comment by AsylumDreams** [comment]
'# ╔════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ default.yml file of the AreaShop plugin created by NLThijs48, Github can be found at https://github.com/NLthijs48/AreaShop ║
# ║ All settings below are default settings and can be overridden by group settings or individual region settings              ║
# ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
# ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
# │ GENERAL: Options for all regions                                                                                           │
# └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘  
general:
  ## Set this to true to enable saving/restoring for regions as specified in the profile below, which is specified in the config
  enableRestore: true
  ## The schematic profile as specified in the config
  schematicProfile: 'default'
  ## The event commands profile as specified in the config
  eventCommandProfile: 'default'
  ## The profile for the format of the sign as specified in the config
  signProfile: 'default'
  ## The profile for the WorldGuard flags as specified in the config
  flagProfile: 'default'
  ## The y location within the region to start searching for safe teleport spots (x and z will be in the middle of the region)
  ## Possible values: bottom, middle, top
  teleportLocationY: bottom
  ## If true the teleportation algorithm only allows telportation to inside the region, otherwise it will expand algorithm
  ## a cube from the starting point to check for safe spots (then it could end outside the region)
  ## If you set a teleport location outside of the region with /as settp then setting this to true breaks that teleport (players cannot use it)
  teleportIntoRegion: true
  ## Same as above, but then for when you teleport to the sign of a region instead of the region itself
  teleportToSignIntoRegion: true
  ## Restricts the /as buy and /as rent commands to the world of the region 
  ## Usefull if you have diffrent economies for different worlds
  restrictedToWorld: true
  ## Restricts the /as buy and /as rent commands to the region itself (player needs to be inside)
  restrictedToRegion: true


# ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
# │ RENT: Options for rent regions                                                                                             │
# └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
rent:
  ## The default price of a renting region
  price: 1000
  ## The default duration of a renting region, you can find all time indicators in config.yml below the RENTING header
  duration: '5 day'
  ## The percentage of the renting price you get back if you unrent the region (price of time left will be multiplied by this/100)
  moneyBack: 20
  ## Maximum number of extends a player can do (-1 for infinite, 0 for no extending)
  maxExtends: 3
  ## The Maximum time they can have the region rented in advance (minutes, -1 for infinite)
  ## If you set this lower then the rent duration then players will not be able to rent the region 
  ## (because it always exceeds the maxRentTime in that case) 
  maxRentTime: 40320
  ## Automatically unrent the region after the specified number of minutes between the last login time of the renter and the current time
  ## -1 means never, 1440 is one day, 43200 is one month, 525600 is one year
  inactiveTimeUntilUnrent: 21600
  ## If a region of a player has less then this time left when he joins the server he will get a warning
  ## You can find all time indicators in config.yml below the RENTING header, change to '' to disable
  warningOnLoginTime: '1 day'
  ## The profile for the expiration warnings as specified in the config
  expirationWarningProfile: 'default'


# ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
# │ BUY: Options for buy regions                                                                                               │
# └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
buy:
  ## The default price of a buying region
  price: 10000
  ## The percentage of the buying price you get back if you sell the region
  moneyBack: 80
  ## Automatically sell the region after the specified number of minutes between the last login time of the buyer and the current time
  ## -1 mean never, 1440 is one day, 43200 is one month, 525600 is one year
   inactiveTimeUntilSell: 21600'

**Comment by NLthijs48** [comment]
Sorry for replying a bit late, but your pastebin is not accesible, it says that it has been removed. I also saw that just after you posted you reply but forgot about it later. So you need to upload it again somewhere.

**Comment by AsylumDreams** [comment]
Hmm that's strange.
 Don't think I've ever known a public pastebin to be removed :/

  I tihnk it may have been my skipping the captcha.
 I just grabbed the URL and closed it after submitting rather than scrolling down to affirm it.

http://pastebin.com/Tzf2ek2H

 Which I did do for this one ^_^

**Comment by NLthijs48** [comment]
Found the problem, you have 3 spaces in front of the `inactiveTimeUntilSell` settings instead of 2. Simply change that and it should load correctly.

**Comment by AsylumDreams** [comment]
Well I'm moronic. Surprised the parser didn't catch that :/ Especially as I just tested it now and put the space back in and it showed up. I doubt I forgot to test that as it's pretty much a default practice, but I have been slightly overrun this week. Regardless, kudos and thanks muchly ^_^
Date: Sat, 28 Nov 2015 10:37:46 -0800
